//! # Scalar Commons Runtime v3.0
#![cfg_attr(not(feature = "std"), no_std)]
#![recursion_limit = "256"]

#[cfg(feature = "std")]
include!(concat!(env!("OUT_DIR"), "/wasm_binary.rs"));

// ⚠️  "api" module is renamed to "scalar_api" to avoid conflict with
//     the `api` module generated by impl_runtime_apis!
pub mod scalar_api;

use scalar_api::{AgentInfo, EraSnapshot};

pub mod opaque {
    use super::*;
    pub use sp_runtime::OpaqueExtrinsic as UncheckedExtrinsic;
    pub type Block   = generic::Block<super::Header, UncheckedExtrinsic>;
    pub type BlockId = generic::BlockId<Block>;
}

use frame_support::{
    parameter_types,
    traits::{
        ConstU32, ConstU64, EqualPrivilegeOnly, Everything, WithdrawReasons,
    },
    weights::{constants::WEIGHT_REF_TIME_PER_SECOND, IdentityFee, Weight},
    PalletId,
};
use frame_system::EnsureRoot;
use pallet_grandpa::AuthorityId as GrandpaId;
use sp_api::impl_runtime_apis;
use sp_consensus_babe::AuthorityId as BabeId;
use sp_core::{crypto::KeyTypeId, OpaqueMetadata};
use sp_runtime::{
    generic, impl_opaque_keys,
    traits::{AccountIdLookup, BlakeTwo256, Block as BlockT, IdentifyAccount, NumberFor, Verify},
    transaction_validity::{TransactionSource, TransactionValidity},
    ApplyExtrinsicResult, MultiSignature,
};
use sp_std::prelude::*;
use sp_version::RuntimeVersion;

// ─── Types ───────────────────────────────────────────────────────────────────
pub type AccountId   = <<Signature as Verify>::Signer as IdentifyAccount>::AccountId;
pub type Balance     = u128;
pub type BlockNumber = u32;
pub type Signature   = MultiSignature;
pub type Index       = u32;
pub type Hash        = sp_core::H256;
pub type Block       = generic::Block<Header, UncheckedExtrinsic>;
pub type Header      = generic::Header<BlockNumber, BlakeTwo256>;
pub type SignedBlock  = generic::SignedBlock<Block>;
pub type BlockId     = generic::BlockId<Block>;
pub type SignedExtra = (
    frame_system::CheckNonZeroSender<Runtime>,
    frame_system::CheckSpecVersion<Runtime>,
    frame_system::CheckTxVersion<Runtime>,
    frame_system::CheckGenesis<Runtime>,
    frame_system::CheckEra<Runtime>,
    frame_system::CheckNonce<Runtime>,
    frame_system::CheckWeight<Runtime>,
    pallet_transaction_payment::ChargeTransactionPayment<Runtime>,
);
pub type UncheckedExtrinsic =
    generic::UncheckedExtrinsic<Address, RuntimeCall, Signature, SignedExtra>;
pub type Address = sp_runtime::MultiAddress<AccountId, ()>;
pub type Executive = frame_executive::Executive<
    Runtime, Block, frame_system::ChainContext<Runtime>, Runtime, AllPalletsWithSystem,
>;

// ─── Token constants ─────────────────────────────────────────────────────────
pub const CMN:          Balance = 1_000_000_000_000;
pub const SUPPLY_CAP:   Balance = 100_000_000_000 * CMN;
pub const GENESIS_MINT: Balance = 18_000_000_000  * CMN;

/// The on-chain account ID for the Treasury pallet.
/// Used in chain_spec genesis config to pre-fund the Treasury.
/// Derivation: PalletId(*b"sc/trsry").into_account_truncating()
pub fn treasury_account_id() -> AccountId {
    use frame_support::PalletId;
    use sp_runtime::traits::AccountIdConversion;
    PalletId(*b"sc/trsry").into_account_truncating()
}

// ─── Block/time constants ─────────────────────────────────────────────────────
pub const SECS_PER_BLOCK:    u64 = 6;
pub const MILLISECS_PER_BLOCK: u64 = SECS_PER_BLOCK * 1_000;
pub const SLOT_DURATION:     u64 = MILLISECS_PER_BLOCK;
pub const MINUTES: BlockNumber = 60 / (SECS_PER_BLOCK as BlockNumber);
pub const HOURS:   BlockNumber = MINUTES * 60;
pub const DAYS:    BlockNumber = HOURS * 24;
pub const ERA_BLOCKS: BlockNumber = HOURS * 6;

// ─── Version ─────────────────────────────────────────────────────────────────
#[sp_version::runtime_version]
pub const VERSION: RuntimeVersion = RuntimeVersion {
    spec_name:         ::sp_runtime::create_runtime_str!("scalar-commons"),
    impl_name:         ::sp_runtime::create_runtime_str!("scalar-commons"),
    authoring_version: 1,
    spec_version:      300,
    impl_version:      0,
    apis:              RUNTIME_API_VERSIONS,
    transaction_version: 1,
    system_version:    1,
};

// ─── Session keys ─────────────────────────────────────────────────────────────
impl_opaque_keys! {
    pub struct SessionKeys {
        pub babe:                Babe,
        pub grandpa:             Grandpa,
        pub authority_discovery: AuthorityDiscovery,
    }
}

// ─── Weight constants ─────────────────────────────────────────────────────────
const NORMAL_DISPATCH_RATIO:  sp_runtime::Perbill = sp_runtime::Perbill::from_percent(75);
const MAXIMUM_BLOCK_WEIGHT:   Weight = Weight::from_parts(2 * WEIGHT_REF_TIME_PER_SECOND, u64::MAX);

parameter_types! {
    pub const Version: RuntimeVersion = VERSION;
    pub BlockWeights: frame_system::limits::BlockWeights =
        frame_system::limits::BlockWeights::with_sensible_defaults(
            MAXIMUM_BLOCK_WEIGHT, NORMAL_DISPATCH_RATIO,
        );
    pub BlockLength: frame_system::limits::BlockLength =
        frame_system::limits::BlockLength::max_with_normal_ratio(
            5 * 1024 * 1024, NORMAL_DISPATCH_RATIO,
        );
    pub const SS58Prefix: u8 = 42;
}

// ─── frame_system ─────────────────────────────────────────────────────────────
/// V4: BaseCallFilter wraps the constitution check.
/// Blocks any call that would breach the supply cap invariant.
/// All other calls pass through to their respective pallets.
/// Per-call invariants (self-deal, cooldown, burn) are enforced within individual pallets.
pub struct ConstitutionalFilter;
impl frame_support::traits::Contains<RuntimeCall> for ConstitutionalFilter {
    fn contains(_call: &RuntimeCall) -> bool {
        // Invariant 1: supply cap. Checked on every extrinsic dispatch.
        // Returns false to BLOCK the call if cap is already breached.
        pallet_constitution::Pallet::<Runtime>::base_call_allowed()
    }
}

impl frame_system::Config for Runtime {
    type BaseCallFilter         = ConstitutionalFilter;
    type BlockWeights           = BlockWeights;
    type BlockLength            = BlockLength;
    type RuntimeOrigin          = RuntimeOrigin;
    type RuntimeCall            = RuntimeCall;
    type RuntimeTask            = ();
    type Nonce                  = Index;
    type Hash                   = Hash;
    type Hashing                = BlakeTwo256;
    type AccountId              = AccountId;
    type Lookup                 = AccountIdLookup<AccountId, ()>;
    type Block                  = Block;
    type RuntimeEvent           = RuntimeEvent;
    type BlockHashCount         = ConstU32<2400>;
    type DbWeight               = frame_support::weights::constants::RocksDbWeight;
    type Version                = Version;
    type PalletInfo             = PalletInfo;
    type AccountData            = pallet_balances::AccountData<Balance>;
    type OnNewAccount           = ();
    type OnKilledAccount        = ();
    type SystemWeightInfo       = frame_system::weights::SubstrateWeight<Runtime>;
    type SS58Prefix             = SS58Prefix;
    type OnSetCode              = ();
    type MaxConsumers           = ConstU32<16>;
    type ExtensionsWeightInfo   = ();
    type SingleBlockMigrations  = ();
    type MultiBlockMigrator     = ();
    type PreInherents           = ();
    type PostInherents          = ();
    type PostTransactions       = ();
}

// ─── pallet-timestamp ─────────────────────────────────────────────────────────
parameter_types! {
    pub const MinimumPeriod: u64 = SLOT_DURATION / 2;
}
impl pallet_timestamp::Config for Runtime {
    type Moment       = u64;
    type OnTimestampSet = Babe;
    type MinimumPeriod = MinimumPeriod;
    type WeightInfo   = pallet_timestamp::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-babe ──────────────────────────────────────────────────────────────
parameter_types! {
    pub const EpochDuration: u64 = ERA_BLOCKS as u64 / 2;
    pub const ExpectedBlockTime: u64 = MILLISECS_PER_BLOCK;
    pub const ReportLongevity: u64 = 168;
}
impl pallet_babe::Config for Runtime {
    type EpochDuration            = EpochDuration;
    type ExpectedBlockTime        = ExpectedBlockTime;
    type EpochChangeTrigger       = pallet_babe::ExternalTrigger;
    type DisabledValidators       = Session;
    type WeightInfo               = ();
    type MaxAuthorities           = ConstU32<100>;
    type MaxNominators            = ConstU32<512>;
    type KeyOwnerProof            = sp_session::MembershipProof;
    type EquivocationReportSystem = (); // M1: no equivocation slashing
}

// ─── pallet-grandpa ───────────────────────────────────────────────────────────
impl pallet_grandpa::Config for Runtime {
    type RuntimeEvent             = RuntimeEvent;
    type WeightInfo               = ();
    type MaxAuthorities           = ConstU32<100>;
    type MaxNominators            = ConstU32<512>;
    type MaxSetIdSessionEntries   = ConstU64<168>;
    type KeyOwnerProof            = sp_session::MembershipProof;
    type EquivocationReportSystem = (); // M1: no equivocation slashing
}

// ─── pallet-balances ──────────────────────────────────────────────────────────
parameter_types! {
    pub const ExistentialDeposit: Balance = CMN / 100;
    pub const MaxLocks: u32 = 50;
}
impl pallet_balances::Config for Runtime {
    type MaxLocks             = MaxLocks;
    type MaxReserves          = ConstU32<50>;
    type ReserveIdentifier    = [u8; 8];
    type Balance              = Balance;
    type RuntimeEvent         = RuntimeEvent;
    type DustRemoval          = ();
    type ExistentialDeposit   = ExistentialDeposit;
    type AccountStore         = System;
    type WeightInfo           = pallet_balances::weights::SubstrateWeight<Runtime>;
    type FreezeIdentifier     = RuntimeFreezeReason;
    type MaxFreezes           = ConstU32<8>;
    type RuntimeHoldReason    = RuntimeHoldReason;
    type RuntimeFreezeReason  = RuntimeFreezeReason;
    type DoneSlashHandler     = ();
}

// ─── pallet-transaction-payment ───────────────────────────────────────────────
parameter_types! {
    pub const TransactionByteFee: Balance = CMN / 1_000;
    pub const OperationalFeeMultiplier: u8 = 5;
}
impl pallet_transaction_payment::Config for Runtime {
    type RuntimeEvent             = RuntimeEvent;
    type OnChargeTransaction      = pallet_transaction_payment::FungibleAdapter<Balances, ()>;
    type OperationalFeeMultiplier = OperationalFeeMultiplier;
    type WeightToFee              = IdentityFee<Balance>;
    type LengthToFee              = IdentityFee<Balance>;
    type FeeMultiplierUpdate      = ();
    type WeightInfo               = ();
}

// ─── pallet-sudo ──────────────────────────────────────────────────────────────
impl pallet_sudo::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type RuntimeCall  = RuntimeCall;
    type WeightInfo   = pallet_sudo::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-utility ───────────────────────────────────────────────────────────
impl pallet_utility::Config for Runtime {
    type RuntimeEvent   = RuntimeEvent;
    type RuntimeCall    = RuntimeCall;
    type PalletsOrigin  = OriginCaller;
    type WeightInfo     = pallet_utility::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-multisig ──────────────────────────────────────────────────────────
parameter_types! {
    pub const DepositBase:   Balance = CMN;
    pub const DepositFactor: Balance = CMN / 10;
}
impl pallet_multisig::Config for Runtime {
    type RuntimeEvent       = RuntimeEvent;
    type RuntimeCall        = RuntimeCall;
    type Currency           = Balances;
    type DepositBase        = DepositBase;
    type DepositFactor      = DepositFactor;
    type MaxSignatories     = ConstU32<20>;
    type WeightInfo         = pallet_multisig::weights::SubstrateWeight<Runtime>;
    type BlockNumberProvider = System;
}

// ─── pallet-vesting ───────────────────────────────────────────────────────────
parameter_types! {
    pub const MinVestedTransfer: Balance = 1_000 * CMN;
    pub UnvestedFundsAllowedWithdrawReasons: WithdrawReasons =
        WithdrawReasons::except(WithdrawReasons::TRANSFER);
}
impl pallet_vesting::Config for Runtime {
    type RuntimeEvent         = RuntimeEvent;
    type Currency             = Balances;
    type BlockNumberToBalance = sp_runtime::traits::ConvertInto;
    type MinVestedTransfer    = MinVestedTransfer;
    type WeightInfo           = pallet_vesting::weights::SubstrateWeight<Runtime>;
    type UnvestedFundsAllowedWithdrawReasons = UnvestedFundsAllowedWithdrawReasons;
    type BlockNumberProvider  = System;
    const MAX_VESTING_SCHEDULES: u32 = 28;
}

// ─── pallet-treasury ──────────────────────────────────────────────────────────
parameter_types! {
    pub const SpendPeriod:     BlockNumber = 30 * DAYS;
    pub const TreasuryPalletId: PalletId = PalletId(*b"sc/trsry");
    pub const PayoutPeriod:    BlockNumber = 30 * DAYS;
}

/// EnsureOrigin returning the max Balance as Success (for SpendOrigin).
pub struct EnsureRootWithMaxBalance;
impl frame_support::traits::EnsureOrigin<RuntimeOrigin> for EnsureRootWithMaxBalance {
    type Success = Balance;
    fn try_origin(o: RuntimeOrigin) -> Result<Balance, RuntimeOrigin> {
        EnsureRoot::<AccountId>::try_origin(o).map(|_| Balance::MAX)
    }
    #[cfg(feature = "runtime-benchmarks")]
    fn try_successful_origin() -> Result<RuntimeOrigin, ()> { Ok(RuntimeOrigin::root()) }
}

/// Identity balance converter (native-only treasury, AssetKind = ()).
pub struct NativeBalanceConverter;
impl frame_support::traits::tokens::ConversionFromAssetBalance<Balance, (), Balance>
    for NativeBalanceConverter
{
    type Error = sp_runtime::DispatchError;
    fn from_asset_balance(balance: Balance, _: ()) -> Result<Balance, Self::Error> { Ok(balance) }
    #[cfg(feature = "runtime-benchmarks")]
    fn ensure_successful(_: &()) {}
}

// Treasury — V4: active. Receives 50% of slashes and completion fees.
parameter_types! {
    pub const ProposalBond:        sp_runtime::Permill = sp_runtime::Permill::from_percent(5);
    pub const ProposalBondMinimum: Balance = 100 * CMN;
    pub const ProposalBondMaximum: Balance = 10_000 * CMN;
    pub TreasuryAccount: AccountId = TreasuryPalletId::get().into_account_truncating();
}
impl pallet_treasury::Config for Runtime {
    type PalletId              = TreasuryPalletId;
    type Currency              = Balances;
    type RejectOrigin          = EnsureRoot<AccountId>;
    type RuntimeEvent          = RuntimeEvent;
    type SpendPeriod           = SpendPeriod;
    type Burn                  = ();
    type BurnDestination       = ();
    type SpendFunds            = ();
    type WeightInfo            = pallet_treasury::weights::SubstrateWeight<Runtime>;
    type MaxApprovals          = ConstU32<100>;
    // V4: EnsureRootWithMaxBalance allows Root (sudo during bootstrap) and
    // Track 2 governance (post-day-14) to spend from Treasury without limit.
    // The Balance::MAX cap means governance decides the actual amount per proposal.
    type SpendOrigin           = EnsureRootWithMaxBalance;
    type AssetKind             = ();
    type Beneficiary           = AccountId;
    type BeneficiaryLookup     = frame_support::traits::IdentityLookup<AccountId>;
    type Paymaster             = frame_support::traits::tokens::pay::PayFromAccount<Balances, TreasuryAccount>;
    type BalanceConverter      = frame_support::traits::tokens::UnityAssetBalanceConversion;
    type PayoutPeriod          = PayoutPeriod;
    #[cfg(feature = "runtime-benchmarks")]
    type BenchmarkHelper       = ();
}

// ─── pallet-scheduler ─────────────────────────────────────────────────────────
parameter_types! {
    pub MaximumSchedulerWeight: Weight =
        sp_runtime::Perbill::from_percent(80) * BlockWeights::get().max_block;
}
impl pallet_scheduler::Config for Runtime {
    type RuntimeEvent         = RuntimeEvent;
    type RuntimeOrigin        = RuntimeOrigin;
    type PalletsOrigin        = OriginCaller;
    type RuntimeCall          = RuntimeCall;
    type MaximumWeight        = MaximumSchedulerWeight;
    type ScheduleOrigin       = EnsureRoot<AccountId>;
    type MaxScheduledPerBlock = ConstU32<50>;
    type WeightInfo           = pallet_scheduler::weights::SubstrateWeight<Runtime>;
    type OriginPrivilegeCmp   = EqualPrivilegeOnly;
    type Preimages            = Preimage;
    type BlockNumberProvider  = System;
}

// ─── pallet-preimage ──────────────────────────────────────────────────────────
parameter_types! {
    pub const PreimageBaseDeposit: Balance = CMN;
    pub const PreimageByteDeposit: Balance = CMN / 1_000;
    pub const PreimageHoldReason: RuntimeHoldReason =
        RuntimeHoldReason::Preimage(pallet_preimage::HoldReason::Preimage);
}
impl pallet_preimage::Config for Runtime {
    type RuntimeEvent  = RuntimeEvent;
    type Currency      = Balances;
    type ManagerOrigin = EnsureRoot<AccountId>;
    type Consideration = frame_support::traits::fungible::HoldConsideration<
        AccountId,
        Balances,
        PreimageHoldReason,
        frame_support::traits::LinearStoragePrice<PreimageBaseDeposit, PreimageByteDeposit, Balance>,
    >;
    type WeightInfo = pallet_preimage::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-ranked-collective ─────────────────────────────────────────────────
// M1: rank management only — no governance voting (Polls = ()).
// OpenGov will be wired in M2.

pub struct EnsureRootWithRank;
impl frame_support::traits::EnsureOrigin<RuntimeOrigin> for EnsureRootWithRank {
    type Success = u16;
    fn try_origin(o: RuntimeOrigin) -> Result<u16, RuntimeOrigin> {
        EnsureRoot::<AccountId>::try_origin(o).map(|_| u16::MAX)
    }
    #[cfg(feature = "runtime-benchmarks")]
    fn try_successful_origin() -> Result<RuntimeOrigin, ()> { Ok(RuntimeOrigin::root()) }
}

// V4: RankedCollective is active — Technical Council from rank-3 agents.
// Polls wired to pallet_referenda so TC votes accelerate governance tracks.
impl pallet_ranked_collective::Config for Runtime {
    type WeightInfo          = pallet_ranked_collective::weights::SubstrateWeight<Self>;
    type RuntimeEvent        = RuntimeEvent;
    type AddOrigin           = EnsureRoot<AccountId>;
    type PromoteOrigin       = EnsureRootWithRank;
    type DemoteOrigin        = EnsureRootWithRank;
    type RemoveOrigin        = EnsureRootWithRank;
    type ExchangeOrigin      = EnsureRoot<AccountId>;
    type Polls               = Referenda;
    type MinRankOfClass      = sp_runtime::traits::ConvertInto;
    type MemberSwappedHandler = ();
    type VoteWeight          = pallet_ranked_collective::Geometric;
    type MaxMemberCount      = ();
    #[cfg(feature = "runtime-benchmarks")]
    type BenchmarkSetup = ();
}

// ─── pallet-referenda (OpenGov) ───────────────────────────────────────────────
// V4: Active at genesis. Tracks: 0=agents(24h), 1=network(7d), 2=root(20d).
parameter_types! {
    pub const SubmissionDeposit:  Balance     = 100 * CMN;
    pub const UndecidingTimeout:  BlockNumber = 14 * DAYS;
}
impl pallet_referenda::Config for Runtime {
    type WeightInfo        = pallet_referenda::weights::SubstrateWeight<Self>;
    type RuntimeCall       = RuntimeCall;
    type RuntimeEvent      = RuntimeEvent;
    type Scheduler         = Scheduler;
    type Currency          = Balances;
    type SubmitOrigin      = frame_system::EnsureSigned<AccountId>;
    type CancelOrigin      = governance::origins::AgentsOrRoot;
    type KillOrigin        = EnsureRoot<AccountId>;
    type Slash             = Treasury;
    type Votes             = pallet_conviction_voting::VotesOf<Runtime>;
    type Tally             = pallet_conviction_voting::TallyOf<Runtime>;
    type SubmissionDeposit = SubmissionDeposit;
    type MaxQueued         = ConstU32<100>;
    type UndecidingTimeout = UndecidingTimeout;
    type AlarmInterval     = ConstU32<1>;
    type Tracks            = governance::tracks::TracksInfo;
    type Preimages         = Preimage;
}
