//! # Scalar Commons Runtime v3.0
#![cfg_attr(not(feature = "std"), no_std)]
#![recursion_limit = "256"]

#[cfg(feature = "std")]
include!(concat!(env!("OUT_DIR"), "/wasm_binary.rs"));

// ⚠️  "api" module is renamed to "scalar_api" to avoid conflict with
//     the `api` module generated by impl_runtime_apis!
pub mod scalar_api;

// OpenGov configuration: custom origins and referenda tracks. Referenced below
// as `governance::origins::*` / `governance::tracks::*`.
pub mod governance;

use scalar_api::{AgentInfo, EraSnapshot};

pub mod opaque {
    use super::*;
    pub use sp_runtime::OpaqueExtrinsic as UncheckedExtrinsic;
    pub type Block   = generic::Block<super::Header, UncheckedExtrinsic>;
    pub type BlockId = generic::BlockId<Block>;
}

use frame_support::{
    parameter_types,
    traits::tokens::imbalance::ResolveTo,
    traits::{
        ConstU32, ConstU64, EqualPrivilegeOnly, Everything, WithdrawReasons,
    },
    weights::{constants::WEIGHT_REF_TIME_PER_SECOND, IdentityFee, Weight},
    PalletId,
};
use frame_system::{EnsureRoot, EnsureRootWithSuccess};
use pallet_grandpa::AuthorityId as GrandpaId;
use sp_api::impl_runtime_apis;
use sp_consensus_babe::AuthorityId as BabeId;
use sp_core::{crypto::KeyTypeId, OpaqueMetadata};
use sp_runtime::{
    generic, impl_opaque_keys,
    traits::{
        AccountIdConversion, AccountIdLookup, BlakeTwo256, Block as BlockT, IdentifyAccount,
        IdentityLookup, NumberFor, Verify,
    },
    transaction_validity::{TransactionSource, TransactionValidity},
    ApplyExtrinsicResult, MultiSignature,
};
use sp_std::prelude::*;
use sp_version::RuntimeVersion;

// ─── Types ───────────────────────────────────────────────────────────────────
pub type AccountId   = <<Signature as Verify>::Signer as IdentifyAccount>::AccountId;
pub type Balance     = u128;
pub type BlockNumber = u32;
pub type Signature   = MultiSignature;
pub type Index       = u32;
pub type Hash        = sp_core::H256;
pub type Block       = generic::Block<Header, UncheckedExtrinsic>;
pub type Header      = generic::Header<BlockNumber, BlakeTwo256>;
pub type SignedBlock  = generic::SignedBlock<Block>;
pub type BlockId     = generic::BlockId<Block>;
pub type SignedExtra = (
    frame_system::CheckNonZeroSender<Runtime>,
    frame_system::CheckSpecVersion<Runtime>,
    frame_system::CheckTxVersion<Runtime>,
    frame_system::CheckGenesis<Runtime>,
    frame_system::CheckEra<Runtime>,
    frame_system::CheckNonce<Runtime>,
    frame_system::CheckWeight<Runtime>,
    pallet_transaction_payment::ChargeTransactionPayment<Runtime>,
);
pub type UncheckedExtrinsic =
    generic::UncheckedExtrinsic<Address, RuntimeCall, Signature, SignedExtra>;
pub type Address = sp_runtime::MultiAddress<AccountId, ()>;
pub type Executive = frame_executive::Executive<
    Runtime, Block, frame_system::ChainContext<Runtime>, Runtime, AllPalletsWithSystem,
>;

// ─── Token constants ─────────────────────────────────────────────────────────
pub const CMN:          Balance = 1_000_000_000_000;
pub const SUPPLY_CAP:   Balance = 100_000_000_000 * CMN;
pub const GENESIS_MINT: Balance = 18_000_000_000  * CMN;

/// The on-chain account ID for the Treasury pallet.
/// Used in chain_spec genesis config to pre-fund the Treasury.
/// Derivation: PalletId(*b"sc/trsry").into_account_truncating()
pub fn treasury_account_id() -> AccountId {
    use frame_support::PalletId;
    use sp_runtime::traits::AccountIdConversion;
    PalletId(*b"sc/trsry").into_account_truncating()
}

// ─── Block/time constants ─────────────────────────────────────────────────────
pub const SECS_PER_BLOCK:    u64 = 6;
pub const MILLISECS_PER_BLOCK: u64 = SECS_PER_BLOCK * 1_000;
pub const SLOT_DURATION:     u64 = MILLISECS_PER_BLOCK;
pub const MINUTES: BlockNumber = 60 / (SECS_PER_BLOCK as BlockNumber);
pub const HOURS:   BlockNumber = MINUTES * 60;
pub const DAYS:    BlockNumber = HOURS * 24;
pub const ERA_BLOCKS: BlockNumber = HOURS * 6;

// ─── Version ─────────────────────────────────────────────────────────────────
#[sp_version::runtime_version]
pub const VERSION: RuntimeVersion = RuntimeVersion {
    spec_name:         ::sp_runtime::create_runtime_str!("scalar-commons"),
    impl_name:         ::sp_runtime::create_runtime_str!("scalar-commons"),
    authoring_version: 1,
    // 300 -> 301: added pallet-referenda Instance2 (RankedPolls) at index 41.
    // Adding a pallet changes the storage layout, which CLAUDE.md requires be
    // accompanied by a spec_version bump. No migration is needed: this runtime
    // has never produced a WASM blob, so there is no live chain state to move.
    spec_version:      301,
    impl_version:      0,
    apis:              RUNTIME_API_VERSIONS,
    transaction_version: 1,
    system_version:    1,
};

// ─── Session keys ─────────────────────────────────────────────────────────────
impl_opaque_keys! {
    pub struct SessionKeys {
        pub babe:                Babe,
        pub grandpa:             Grandpa,
        pub authority_discovery: AuthorityDiscovery,
    }
}

// ─── Weight constants ─────────────────────────────────────────────────────────
const NORMAL_DISPATCH_RATIO:  sp_runtime::Perbill = sp_runtime::Perbill::from_percent(75);
const MAXIMUM_BLOCK_WEIGHT:   Weight = Weight::from_parts(2 * WEIGHT_REF_TIME_PER_SECOND, u64::MAX);

parameter_types! {
    pub const Version: RuntimeVersion = VERSION;
    pub BlockWeights: frame_system::limits::BlockWeights =
        frame_system::limits::BlockWeights::with_sensible_defaults(
            MAXIMUM_BLOCK_WEIGHT, NORMAL_DISPATCH_RATIO,
        );
    pub BlockLength: frame_system::limits::BlockLength =
        frame_system::limits::BlockLength::max_with_normal_ratio(
            5 * 1024 * 1024, NORMAL_DISPATCH_RATIO,
        );
    pub const SS58Prefix: u8 = 42;
}

// ─── frame_system ─────────────────────────────────────────────────────────────
/// V4: BaseCallFilter wraps the constitution check.
/// Blocks any call that would breach the supply cap invariant.
/// All other calls pass through to their respective pallets.
/// Per-call invariants (self-deal, cooldown, burn) are enforced within individual pallets.
pub struct ConstitutionalFilter;
impl frame_support::traits::Contains<RuntimeCall> for ConstitutionalFilter {
    fn contains(_call: &RuntimeCall) -> bool {
        // Invariant 1: supply cap. Checked on every extrinsic dispatch.
        // Returns false to BLOCK the call if cap is already breached.
        pallet_constitution::Pallet::<Runtime>::base_call_allowed()
    }
}

impl frame_system::Config for Runtime {
    type BaseCallFilter         = ConstitutionalFilter;
    type BlockWeights           = BlockWeights;
    type BlockLength            = BlockLength;
    type RuntimeOrigin          = RuntimeOrigin;
    type RuntimeCall            = RuntimeCall;
    type RuntimeTask            = ();
    type Nonce                  = Index;
    type Hash                   = Hash;
    type Hashing                = BlakeTwo256;
    type AccountId              = AccountId;
    type Lookup                 = AccountIdLookup<AccountId, ()>;
    type Block                  = Block;
    type RuntimeEvent           = RuntimeEvent;
    type BlockHashCount         = ConstU32<2400>;
    type DbWeight               = frame_support::weights::constants::RocksDbWeight;
    type Version                = Version;
    type PalletInfo             = PalletInfo;
    type AccountData            = pallet_balances::AccountData<Balance>;
    type OnNewAccount           = ();
    type OnKilledAccount        = ();
    type SystemWeightInfo       = frame_system::weights::SubstrateWeight<Runtime>;
    type SS58Prefix             = SS58Prefix;
    type OnSetCode              = ();
    type MaxConsumers           = ConstU32<16>;
    type ExtensionsWeightInfo   = ();
    type SingleBlockMigrations  = ();
    type MultiBlockMigrator     = ();
    type PreInherents           = ();
    type PostInherents          = ();
    type PostTransactions       = ();
}

// ─── pallet-timestamp ─────────────────────────────────────────────────────────
parameter_types! {
    pub const MinimumPeriod: u64 = SLOT_DURATION / 2;
}
impl pallet_timestamp::Config for Runtime {
    type Moment       = u64;
    type OnTimestampSet = Babe;
    type MinimumPeriod = MinimumPeriod;
    type WeightInfo   = pallet_timestamp::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-babe ──────────────────────────────────────────────────────────────
parameter_types! {
    pub const EpochDuration: u64 = ERA_BLOCKS as u64 / 2;
    pub const ExpectedBlockTime: u64 = MILLISECS_PER_BLOCK;
    pub const ReportLongevity: u64 = 168;
}
impl pallet_babe::Config for Runtime {
    type EpochDuration            = EpochDuration;
    type ExpectedBlockTime        = ExpectedBlockTime;
    type EpochChangeTrigger       = pallet_babe::ExternalTrigger;
    type DisabledValidators       = Session;
    type WeightInfo               = ();
    type MaxAuthorities           = ConstU32<100>;
    type MaxNominators            = ConstU32<512>;
    type KeyOwnerProof            = sp_session::MembershipProof;
    type EquivocationReportSystem = (); // M1: no equivocation slashing
}

// ─── pallet-grandpa ───────────────────────────────────────────────────────────
impl pallet_grandpa::Config for Runtime {
    type RuntimeEvent             = RuntimeEvent;
    type WeightInfo               = ();
    type MaxAuthorities           = ConstU32<100>;
    type MaxNominators            = ConstU32<512>;
    type MaxSetIdSessionEntries   = ConstU64<168>;
    type KeyOwnerProof            = sp_session::MembershipProof;
    type EquivocationReportSystem = (); // M1: no equivocation slashing
}

// ─── pallet-balances ──────────────────────────────────────────────────────────
parameter_types! {
    pub const ExistentialDeposit: Balance = CMN / 100;
    pub const MaxLocks: u32 = 50;
}
impl pallet_balances::Config for Runtime {
    type MaxLocks             = MaxLocks;
    type MaxReserves          = ConstU32<50>;
    type ReserveIdentifier    = [u8; 8];
    type Balance              = Balance;
    type RuntimeEvent         = RuntimeEvent;
    type DustRemoval          = ();
    type ExistentialDeposit   = ExistentialDeposit;
    type AccountStore         = System;
    type WeightInfo           = pallet_balances::weights::SubstrateWeight<Runtime>;
    type FreezeIdentifier     = RuntimeFreezeReason;
    type MaxFreezes           = ConstU32<8>;
    type RuntimeHoldReason    = RuntimeHoldReason;
    type RuntimeFreezeReason  = RuntimeFreezeReason;
    type DoneSlashHandler     = ();
}

// ─── pallet-transaction-payment ───────────────────────────────────────────────
parameter_types! {
    pub const TransactionByteFee: Balance = CMN / 1_000;
    pub const OperationalFeeMultiplier: u8 = 5;
}
impl pallet_transaction_payment::Config for Runtime {
    type RuntimeEvent             = RuntimeEvent;
    type OnChargeTransaction      = pallet_transaction_payment::FungibleAdapter<Balances, ()>;
    type OperationalFeeMultiplier = OperationalFeeMultiplier;
    type WeightToFee              = IdentityFee<Balance>;
    type LengthToFee              = IdentityFee<Balance>;
    type FeeMultiplierUpdate      = ();
    type WeightInfo               = ();
}

// ─── pallet-sudo ──────────────────────────────────────────────────────────────
impl pallet_sudo::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type RuntimeCall  = RuntimeCall;
    type WeightInfo   = pallet_sudo::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-utility ───────────────────────────────────────────────────────────
impl pallet_utility::Config for Runtime {
    type RuntimeEvent   = RuntimeEvent;
    type RuntimeCall    = RuntimeCall;
    type PalletsOrigin  = OriginCaller;
    type WeightInfo     = pallet_utility::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-multisig ──────────────────────────────────────────────────────────
parameter_types! {
    pub const DepositBase:   Balance = CMN;
    pub const DepositFactor: Balance = CMN / 10;
}
impl pallet_multisig::Config for Runtime {
    type RuntimeEvent       = RuntimeEvent;
    type RuntimeCall        = RuntimeCall;
    type Currency           = Balances;
    type DepositBase        = DepositBase;
    type DepositFactor      = DepositFactor;
    type MaxSignatories     = ConstU32<20>;
    type WeightInfo         = pallet_multisig::weights::SubstrateWeight<Runtime>;
    type BlockNumberProvider = System;
}

// ─── pallet-vesting ───────────────────────────────────────────────────────────
parameter_types! {
    pub const MinVestedTransfer: Balance = 1_000 * CMN;
    pub UnvestedFundsAllowedWithdrawReasons: WithdrawReasons =
        WithdrawReasons::except(WithdrawReasons::TRANSFER);
}
impl pallet_vesting::Config for Runtime {
    type RuntimeEvent         = RuntimeEvent;
    type Currency             = Balances;
    type BlockNumberToBalance = sp_runtime::traits::ConvertInto;
    type MinVestedTransfer    = MinVestedTransfer;
    type WeightInfo           = pallet_vesting::weights::SubstrateWeight<Runtime>;
    type UnvestedFundsAllowedWithdrawReasons = UnvestedFundsAllowedWithdrawReasons;
    type BlockNumberProvider  = System;
    const MAX_VESTING_SCHEDULES: u32 = 28;
}

// ─── pallet-treasury ──────────────────────────────────────────────────────────
parameter_types! {
    pub const SpendPeriod:     BlockNumber = 30 * DAYS;
    pub const TreasuryPalletId: PalletId = PalletId(*b"sc/trsry");
    pub const PayoutPeriod:    BlockNumber = 30 * DAYS;
}

/// EnsureOrigin returning the max Balance as Success (for SpendOrigin).
pub struct EnsureRootWithMaxBalance;
impl frame_support::traits::EnsureOrigin<RuntimeOrigin> for EnsureRootWithMaxBalance {
    type Success = Balance;
    fn try_origin(o: RuntimeOrigin) -> Result<Balance, RuntimeOrigin> {
        EnsureRoot::<AccountId>::try_origin(o).map(|_| Balance::MAX)
    }
    #[cfg(feature = "runtime-benchmarks")]
    fn try_successful_origin() -> Result<RuntimeOrigin, ()> { Ok(RuntimeOrigin::root()) }
}

/// Identity balance converter (native-only treasury, AssetKind = ()).
pub struct NativeBalanceConverter;
impl frame_support::traits::tokens::ConversionFromAssetBalance<Balance, (), Balance>
    for NativeBalanceConverter
{
    type Error = sp_runtime::DispatchError;
    fn from_asset_balance(balance: Balance, _: ()) -> Result<Balance, Self::Error> { Ok(balance) }
    #[cfg(feature = "runtime-benchmarks")]
    fn ensure_successful(_: &()) {}
}

// Treasury — V4: active. Receives 50% of slashes and completion fees.
parameter_types! {
    pub const ProposalBond:        sp_runtime::Permill = sp_runtime::Permill::from_percent(5);
    pub const ProposalBondMinimum: Balance = 100 * CMN;
    pub const ProposalBondMaximum: Balance = 10_000 * CMN;
    pub TreasuryAccount: AccountId = TreasuryPalletId::get().into_account_truncating();
}
impl pallet_treasury::Config for Runtime {
    type PalletId              = TreasuryPalletId;
    type Currency              = Balances;
    type RejectOrigin          = EnsureRoot<AccountId>;
    type RuntimeEvent          = RuntimeEvent;
    type SpendPeriod           = SpendPeriod;
    type Burn                  = ();
    type BurnDestination       = ();
    type SpendFunds            = ();
    type WeightInfo            = pallet_treasury::weights::SubstrateWeight<Runtime>;
    type MaxApprovals          = ConstU32<100>;
    // V4: EnsureRootWithMaxBalance allows Root (sudo during bootstrap) and
    // Track 2 governance (post-day-14) to spend from Treasury without limit.
    // The Balance::MAX cap means governance decides the actual amount per proposal.
    type SpendOrigin           = EnsureRootWithMaxBalance;
    type AssetKind             = ();
    type Beneficiary           = AccountId;
    type BeneficiaryLookup     = IdentityLookup<AccountId>;
    type Paymaster             = frame_support::traits::tokens::pay::PayFromAccount<Balances, TreasuryAccount>;
    type BalanceConverter      = frame_support::traits::tokens::UnityAssetBalanceConversion;
    type PayoutPeriod          = PayoutPeriod;
    // New at stable2503: pallets read block numbers through a provider rather
    // than assuming frame_system. System is the local chain clock.
    type BlockNumberProvider   = System;
    #[cfg(feature = "runtime-benchmarks")]
    type BenchmarkHelper       = ();
}

// ─── pallet-scheduler ─────────────────────────────────────────────────────────
parameter_types! {
    pub MaximumSchedulerWeight: Weight =
        sp_runtime::Perbill::from_percent(80) * BlockWeights::get().max_block;
}
impl pallet_scheduler::Config for Runtime {
    type RuntimeEvent         = RuntimeEvent;
    type RuntimeOrigin        = RuntimeOrigin;
    type PalletsOrigin        = OriginCaller;
    type RuntimeCall          = RuntimeCall;
    type MaximumWeight        = MaximumSchedulerWeight;
    type ScheduleOrigin       = EnsureRoot<AccountId>;
    type MaxScheduledPerBlock = ConstU32<50>;
    type WeightInfo           = pallet_scheduler::weights::SubstrateWeight<Runtime>;
    type OriginPrivilegeCmp   = EqualPrivilegeOnly;
    type Preimages            = Preimage;
    type BlockNumberProvider  = System;
}

// ─── pallet-preimage ──────────────────────────────────────────────────────────
parameter_types! {
    pub const PreimageBaseDeposit: Balance = CMN;
    pub const PreimageByteDeposit: Balance = CMN / 1_000;
    pub const PreimageHoldReason: RuntimeHoldReason =
        RuntimeHoldReason::Preimage(pallet_preimage::HoldReason::Preimage);
}
impl pallet_preimage::Config for Runtime {
    type RuntimeEvent  = RuntimeEvent;
    type Currency      = Balances;
    type ManagerOrigin = EnsureRoot<AccountId>;
    type Consideration = frame_support::traits::fungible::HoldConsideration<
        AccountId,
        Balances,
        PreimageHoldReason,
        frame_support::traits::LinearStoragePrice<PreimageBaseDeposit, PreimageByteDeposit, Balance>,
    >;
    type WeightInfo = pallet_preimage::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-ranked-collective ─────────────────────────────────────────────────
// M1: rank management only — no governance voting (Polls = ()).
// OpenGov will be wired in M2.

pub struct EnsureRootWithRank;
impl frame_support::traits::EnsureOrigin<RuntimeOrigin> for EnsureRootWithRank {
    type Success = u16;
    fn try_origin(o: RuntimeOrigin) -> Result<u16, RuntimeOrigin> {
        EnsureRoot::<AccountId>::try_origin(o).map(|_| u16::MAX)
    }
    #[cfg(feature = "runtime-benchmarks")]
    fn try_successful_origin() -> Result<RuntimeOrigin, ()> { Ok(RuntimeOrigin::root()) }
}

// V4: RankedCollective is active — Technical Council from rank-3 agents.
//
// `Polls = RankedPolls` — GOVERNANCE DECISION, see ROUND3.md.
//
// A single pallet-referenda instance has exactly ONE Tally type across all of
// its tracks. ConvictionVoting requires `conviction_voting::TallyOf`;
// RankedCollective requires `ranked_collective::TallyOf`. Pointing both at the
// same `Referenda` instance (as the original code did) is type-impossible on
// any SDK version — this is not drift, it never compiled.
//
// Resolved the way the SDK itself does it (substrate/bin/node/runtime): a
// SECOND referenda instance, `RankedPolls` (Instance2), carrying the ranked
// tally, while `Referenda` keeps the conviction tally for stake-weighted
// OpenGov. The TC therefore votes on its own poll set.
impl pallet_ranked_collective::Config for Runtime {
    type WeightInfo          = pallet_ranked_collective::weights::SubstrateWeight<Self>;
    type RuntimeEvent        = RuntimeEvent;
    type AddOrigin           = EnsureRoot<AccountId>;
    type PromoteOrigin       = EnsureRootWithRank;
    type DemoteOrigin        = EnsureRootWithRank;
    type RemoveOrigin        = EnsureRootWithRank;
    type ExchangeOrigin      = EnsureRoot<AccountId>;
    type Polls               = RankedPolls;
    type MinRankOfClass      = sp_runtime::traits::ConvertInto;
    type MemberSwappedHandler = ();
    type VoteWeight          = pallet_ranked_collective::Geometric;
    type MaxMemberCount      = ();
    #[cfg(feature = "runtime-benchmarks")]
    type BenchmarkSetup = ();
}

// ─── pallet-referenda (OpenGov) ───────────────────────────────────────────────
// V4: Active at genesis. Tracks: 0=agents(24h), 1=network(7d), 2=root(20d).
parameter_types! {
    pub const SubmissionDeposit:  Balance     = 100 * CMN;
    pub const UndecidingTimeout:  BlockNumber = 14 * DAYS;
}
impl pallet_referenda::Config for Runtime {
    type WeightInfo        = pallet_referenda::weights::SubstrateWeight<Self>;
    type RuntimeCall       = RuntimeCall;
    type RuntimeEvent      = RuntimeEvent;
    type Scheduler         = Scheduler;
    type Currency          = Balances;
    type SubmitOrigin      = frame_system::EnsureSigned<AccountId>;
    type CancelOrigin      = governance::origins::AgentsOrRoot;
    type KillOrigin        = EnsureRoot<AccountId>;
    type Slash             = Treasury;
    type Votes             = pallet_conviction_voting::VotesOf<Runtime>;
    type Tally             = pallet_conviction_voting::TallyOf<Runtime>;
    type SubmissionDeposit = SubmissionDeposit;
    type MaxQueued         = ConstU32<100>;
    type UndecidingTimeout = UndecidingTimeout;
    type AlarmInterval     = ConstU32<1>;
    type Tracks            = governance::tracks::TracksInfo;
    type Preimages         = Preimage;
    type BlockNumberProvider = System;
}

// ─── pallet-referenda Instance2: RankedPolls (Technical Council) ──────────────
// The TC's own poll set, carrying the ranked-collective tally. Separate from the
// stake-weighted `Referenda` instance above because one referenda instance can
// only have one Tally type — see the note on pallet_ranked_collective::Config.
// Mirrors substrate/bin/node/runtime's `RankedPolls` (Instance2) at this tag.
//
// Deposits, queue depth, timeout and tracks are deliberately identical to the
// stake instance: this is a transport for the same governance tracks under a
// different electorate, not a second economic regime. No new constants.
impl pallet_referenda::Config<pallet_referenda::Instance2> for Runtime {
    type WeightInfo        = pallet_referenda::weights::SubstrateWeight<Self>;
    type RuntimeCall       = RuntimeCall;
    type RuntimeEvent      = RuntimeEvent;
    type Scheduler         = Scheduler;
    type Currency          = Balances;
    type SubmitOrigin      = frame_system::EnsureSigned<AccountId>;
    type CancelOrigin      = EnsureRoot<AccountId>;
    type KillOrigin        = EnsureRoot<AccountId>;
    type Slash             = Treasury;
    type Votes             = pallet_ranked_collective::Votes;
    type Tally             = pallet_ranked_collective::TallyOf<Runtime>;
    type SubmissionDeposit = SubmissionDeposit;
    type MaxQueued         = ConstU32<100>;
    type UndecidingTimeout = UndecidingTimeout;
    type AlarmInterval     = ConstU32<1>;
    type Tracks            = governance::tracks::TracksInfo;
    type Preimages         = Preimage;
    type BlockNumberProvider = System;
}

// ─── pallet-conviction-voting ─────────────────────────────────────────────────
impl pallet_conviction_voting::Config for Runtime {
    type WeightInfo        = pallet_conviction_voting::weights::SubstrateWeight<Self>;
    type RuntimeEvent      = RuntimeEvent;
    type Currency          = Balances;
    type VoteLockingPeriod = ConstU32<{ ERA_BLOCKS }>;
    type MaxVotes          = ConstU32<512>;
    type MaxTurnout        = frame_support::traits::TotalIssuanceOf<Balances, AccountId>;
    type Polls             = Referenda;
    type BlockNumberProvider = System;
    // New at stable2503: an extension point for reacting to vote/lock changes.
    // No subscribers here, matching the SDK's own runtime.
    type VotingHooks       = ();
}

// ─── pallet-identity ──────────────────────────────────────────────────────────
parameter_types! {
    pub const BasicDeposit:   Balance = 10 * CMN;
    pub const ByteDeposit:    Balance = CMN / 10;
    pub const SubAccountDeposit: Balance = 2 * CMN;
    pub const MaxSubAccounts: u32 = 100;
    pub const MaxAdditionalFields: u32 = 20;
    pub const MaxRegistrars:  u32 = 20;
    pub const UsernameDeposit: Balance = CMN;
    pub const UsernameGracePeriod: BlockNumber = 30 * DAYS;
}
impl pallet_identity::Config for Runtime {
    type RuntimeEvent            = RuntimeEvent;
    type Currency                = Balances;
    type BasicDeposit            = BasicDeposit;
    type ByteDeposit             = ByteDeposit;
    type SubAccountDeposit       = SubAccountDeposit;
    type MaxSubAccounts          = MaxSubAccounts;
    type IdentityInformation     = pallet_identity::legacy::IdentityInfo<MaxAdditionalFields>;
    type MaxRegistrars           = MaxRegistrars;
    type Slashed                 = ();
    type ForceOrigin             = EnsureRoot<AccountId>;
    type RegistrarOrigin         = EnsureRoot<AccountId>;
    type OffchainSignature       = Signature;
    type SigningPublicKey        = <Signature as sp_runtime::traits::Verify>::Signer;
    type UsernameAuthorityOrigin = EnsureRoot<AccountId>;
    type PendingUsernameExpiration = ConstU32<{ 7 * DAYS }>;
    type MaxSuffixLength         = ConstU32<7>;
    type MaxUsernameLength       = ConstU32<32>;
    type WeightInfo              = pallet_identity::weights::SubstrateWeight<Runtime>;
    type UsernameDeposit         = UsernameDeposit;
    type UsernameGracePeriod     = UsernameGracePeriod;
}

// ImOnline removed M1

// ─── pallet-whitelist (V4: TC fast-track — enables 6h governance path) ───────
// WhitelistOrigin: Either Root (sudo during 14-day bootstrap) OR rank-2+ agents (TC post-day-14).
// After sudo removal, only ranked_collective members at rank 2+ can whitelist calls.
// DispatchWhitelistedOrigin: same — only TC can dispatch a whitelisted call.
impl pallet_whitelist::Config for Runtime {
    type RuntimeEvent              = RuntimeEvent;
    type RuntimeCall               = RuntimeCall;
    type WhitelistOrigin           = governance::origins::AgentsOrRoot;
    type DispatchWhitelistedOrigin = governance::origins::AgentsOrRoot;
    type Preimages                 = Preimage;
    type WeightInfo                = pallet_whitelist::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-safe-mode (V4: TC emergency circuit breaker — max 4h pause) ──────
parameter_types! {
    pub const SafeModeMaxDuration: BlockNumber = HOURS * 4;  // TC can pause chain ≤ 4 hours
    /// Permissionless (deposit-funded) safe-mode entry is disabled — safe mode
    /// is root/TC-only, as it was before the stable2503 Config reshape.
    /// `None` disables the path; `Some(0)` would open it to anyone for free.
    pub const NoSafeModeDeposit: Option<Balance> = None;
    /// No deposits are taken, so there is nothing to hold back on release.
    pub const NoReleaseDelay: Option<BlockNumber> = None;
}
/// Calls permitted through SafeMode when the chain is paused.
/// Only governance calls pass — agents can still vote to exit safe mode.
pub struct SafeModeWhitelistedCalls;
impl frame_support::traits::Contains<RuntimeCall> for SafeModeWhitelistedCalls {
    fn contains(call: &RuntimeCall) -> bool {
        matches!(call,
            // Governance must stay live so TC can act and resolve the emergency
            RuntimeCall::Referenda(_)        |
            RuntimeCall::ConvictionVoting(_) |
            RuntimeCall::Whitelist(_)        |
            RuntimeCall::SafeMode(_)         |
            // TC (ranked-collective) must be able to vote to exit SafeMode
            // post-sudo-removal — otherwise there is a deadlock where SafeMode
            // blocks the only actors who can exit it.
            RuntimeCall::RankedCollective(_) |
            // Sudo must stay live during the 14-day bootstrap window
            RuntimeCall::Sudo(_)             |
            // System utility calls (timestamp inherent, etc.) must pass
            RuntimeCall::Timestamp(_)        |
            RuntimeCall::System(_)
        )
    }
}
// stable2503 reshaped this Config. The old origin-gated entry
// (EnterOrigin/ExitOrigin/MaxDuration/EnteredDeposit/ExtendDeposit) is gone;
// entry is now either permissionless-with-deposit or via a Force*Origin that
// returns the duration to pause for. Original intent — "TC emergency circuit
// breaker, root-entered, max 4h" — maps as:
//
//   EnterOrigin  = EnsureRoot   -> ForceEnterOrigin  = EnsureRootWithSuccess<_, 4h>
//   ExitOrigin   = EnsureRoot   -> ForceExitOrigin   = EnsureRoot
//   MaxDuration  = 4h           -> the Success value carried by ForceEnterOrigin
//   EnteredDeposit = ConstU128<0> -> EnterDepositAmount  = None
//   ExtendDeposit  = ConstU128<0> -> ExtendDepositAmount = None
//
// `None` (not `Some(0)`) is the faithful reading of the original: entry was
// root-only, and a zero deposit under the new API would instead let ANY signed
// account put the chain into safe mode for free. None disables that path.
// EnterDuration/ExtendDuration only govern the deposit path, which is off; they
// are set to the same 4h bound for consistency rather than left arbitrary.
//
// No equivalent existed before for: Notify (-> (), no subscribers),
// ForceDepositOrigin (-> root, inert while deposits are disabled),
// ReleaseDelay (-> None, nothing to release).
impl pallet_safe_mode::Config for Runtime {
    type RuntimeEvent          = RuntimeEvent;
    type Currency              = Balances;
    type RuntimeHoldReason     = RuntimeHoldReason;
    type WhitelistedCalls      = SafeModeWhitelistedCalls;
    type EnterDuration         = SafeModeMaxDuration;
    type ExtendDuration        = SafeModeMaxDuration;
    type EnterDepositAmount    = NoSafeModeDeposit;
    type ExtendDepositAmount   = NoSafeModeDeposit;
    type ForceEnterOrigin      = EnsureRootWithSuccess<AccountId, SafeModeMaxDuration>;
    type ForceExtendOrigin     = EnsureRootWithSuccess<AccountId, SafeModeMaxDuration>;
    type ForceExitOrigin       = EnsureRoot<AccountId>;
    type ForceDepositOrigin    = EnsureRoot<AccountId>;
    type Notify                = ();
    type ReleaseDelay          = NoReleaseDelay;
    type WeightInfo            = pallet_safe_mode::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-tx-pause (V4: surgical pause of specific extrinsics) ──────────────
// stable2503 drift: `FullNameOf` was removed (the pallet derives call names
// itself now) and `WhitelistedCalls: Contains<RuntimeCallNameOf<Self>>` was
// added — the set of calls that may NEVER be paused.
//
// `()` is the faithful port: the previous config carried no such protection, so
// every call was pausable, and `()` preserves exactly that. See ROUND3.md — this
// interacts with first principle #3 ("no root-gated liveness") and is flagged
// there for review rather than silently changed here.
impl pallet_tx_pause::Config for Runtime {
    type RuntimeEvent          = RuntimeEvent;
    type RuntimeCall           = RuntimeCall;
    type PauseOrigin           = EnsureRoot<AccountId>;  // TC → root
    type UnpauseOrigin         = EnsureRoot<AccountId>;
    type WhitelistedCalls      = ();
    type MaxNameLen            = ConstU32<256>;
    type WeightInfo            = pallet_tx_pause::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-constitution (V4: 6 invariants as pre-dispatch hooks) ─────────────
parameter_types! {
    // 1% of supply cap = 1,000,000,000 CMN warning buffer
    pub const ConstitutionCapWarning: Balance = 1_000_000_000 * CMN;
    // Invariant 3: unstake cooldown floor — governance cannot go below 7 days
    pub const ConstitutionMinCooldown: BlockNumber = 7 * DAYS;
    // Invariant 4: oracle challenge window floor — governance cannot go below 1 hour
    pub const ConstitutionMinChallengeWindow: BlockNumber = HOURS;
    // Invariant 5: registration burn floor — Sybil cost cannot be removed
    pub const ConstitutionMinBurn: Balance = 10 * CMN;
}
impl pallet_constitution::Config for Runtime {
    type RuntimeEvent          = RuntimeEvent;
    type Currency              = Balances;
    type SupplyCap             = EmissionsSupplyCap;
    type MinUnstakeCooldown    = ConstitutionMinCooldown;
    type MinChallengeWindow    = ConstitutionMinChallengeWindow;
    type MinRegistrationBurn   = ConstitutionMinBurn;
    type CapWarningBuffer      = ConstitutionCapWarning;
}

// ─── pallet-nomination-pools (V4: active — any agent can pool-stake) ─────────
parameter_types! {
    pub const NomPoolsMinJoinBond:   Balance = 100 * CMN;
    pub const NomPoolsMinCreateBond: Balance = 5_000 * CMN;
    pub const NomPoolsMaxPools:      u32     = 1_000;
    pub const NomPoolsMaxMembers:    u32     = 1_000_000;
    pub const NomPoolsPalletId:      PalletId = PalletId(*b"nompools");
}
// Conversion helpers for nomination pools Balance ↔ U256
pub struct BalanceToU256;
impl sp_runtime::traits::Convert<Balance, sp_core::U256> for BalanceToU256 {
    fn convert(b: Balance) -> sp_core::U256 { sp_core::U256::from(b) }
}
pub struct U256ToBalance;
impl sp_runtime::traits::Convert<sp_core::U256, Balance> for U256ToBalance {
    fn convert(u: sp_core::U256) -> Balance {
        u.try_into().unwrap_or(Balance::MAX)
    }
}
impl pallet_nomination_pools::Config for Runtime {
    type RuntimeEvent           = RuntimeEvent;
    type WeightInfo             = pallet_nomination_pools::weights::SubstrateWeight<Runtime>;
    type Currency               = Balances;
    type RuntimeFreezeReason    = RuntimeFreezeReason;
    type RewardCounter          = sp_runtime::FixedU128;
    type BalanceToU256          = BalanceToU256;
    type U256ToBalance          = U256ToBalance;
    type StakeAdapter           = pallet_nomination_pools::adapter::TransferStake<Self, Staking>;
    type PostUnbondingPoolsWindow = ConstU32<4>;
    type MaxMetadataLen         = ConstU32<256>;
    type MaxUnbonding           = ConstU32<8>;
    type PalletId               = NomPoolsPalletId;
    type MaxPointsToBalance     = frame_support::traits::ConstU8<10>;
    type AdminOrigin            = EnsureRoot<AccountId>;
    type BlockNumberProvider    = System;
    // New at stable2503: restricts which accounts may join pools. Nothing =
    // no restriction beyond the pallet's own rules, as in the SDK's runtime.
    type Filter                 = frame_support::traits::Nothing;
}


parameter_types! {
    pub const SessionsPerEra:    sp_staking::SessionIndex = 6;
    pub const BondingDuration:   sp_staking::EraIndex     = 28;
    pub const SlashDeferDuration: sp_staking::EraIndex    = 27;
    pub const MaxExposurePageSize: u32 = 64;
}
pallet_staking_reward_curve::build! {
    const REWARD_CURVE: sp_runtime::curve::PiecewiseLinear<'static> = curve!(
        min_inflation: 0_025_000,
        max_inflation: 0_100_000,
        ideal_stake:   0_500_000,
        falloff:       0_050_000,
        max_piece_count: 40,
        test_precision:  0_005_000,
    );
}
parameter_types! {
    pub const RewardCurve: &'static sp_runtime::curve::PiecewiseLinear<'static> = &REWARD_CURVE;
}

pub struct ScalarStakingBenchmarkConfig;
impl pallet_staking::BenchmarkingConfig for ScalarStakingBenchmarkConfig {
    type MaxValidators = ConstU32<1000>;
    type MaxNominators = ConstU32<1000>;
}

impl pallet_staking::Config for Runtime {
    type Currency                          = Balances;
    type CurrencyBalance                   = Balance;
    type UnixTime                          = Timestamp;
    type CurrencyToVote                    = sp_staking::currency_to_vote::U128CurrencyToVote;
    // stable2503: these take a fungible-based OnUnbalanced. `Treasury` no
    // longer satisfies it (it handles the old Currency NegativeImbalance).
    // ResolveTo<TreasuryAccount, Balances> deposits into the very same treasury
    // account TreasuryPalletId derives, so the destination of funds is unchanged.
    type RewardRemainder                   = ResolveTo<TreasuryAccount, Balances>;
    type RuntimeEvent                      = RuntimeEvent;
    type Slash                             = ResolveTo<TreasuryAccount, Balances>; // equivocation slashes → Treasury
    type Reward                            = ();
    type SessionsPerEra                    = SessionsPerEra;
    type BondingDuration                   = BondingDuration;
    type SlashDeferDuration                = SlashDeferDuration;
    type AdminOrigin                       = EnsureRoot<AccountId>;
    type SessionInterface                  = Self;
    type EraPayout                         = pallet_staking::ConvertCurve<RewardCurve>;
    type NextNewSession                    = Session;
    type HistoryDepth                      = ConstU32<84>;
    type MaxExposurePageSize               = MaxExposurePageSize;
    type ElectionProvider                  = onchain::OnChainExecution<OnChainSeqPhragmen>;
    type GenesisElectionProvider           = onchain::OnChainExecution<OnChainSeqPhragmen>;
    type VoterList                         = VoterList; // pallet_bags_list — Score=VoteWeight=u64 ✓
    type NominationsQuota                  = pallet_staking::FixedNominationsQuota<16>;
    type TargetList                        = pallet_staking::UseValidatorsMap<Self>;
    type MaxUnlockingChunks                = ConstU32<32>;
    type BenchmarkingConfig                = ScalarStakingBenchmarkConfig;
    type WeightInfo                        = pallet_staking::weights::SubstrateWeight<Runtime>;
    type OldCurrency                       = Balances;
    type RuntimeHoldReason                 = RuntimeHoldReason;
    type MaxControllersInDeprecationBatch  = ConstU32<100>;
    type EventListeners                    = ();
    type Filter                            = ();
}

// ─── NPoS election setup ─────────────────────────────────────────────────────
use frame_election_provider_support::{onchain, SequentialPhragmen, VoteWeight};

pub struct OnChainSeqPhragmen;
impl onchain::Config for OnChainSeqPhragmen {
    type System      = Runtime;
    type Solver      = SequentialPhragmen<AccountId, sp_runtime::Perbill>;
    type DataProvider = Staking;
    type WeightInfo  = frame_election_provider_support::weights::SubstrateWeight<Runtime>;
    type MaxWinners  = ConstU32<100>;
    type Bounds      = ElectionBoundsBuilder;
}

parameter_types! {
    pub ElectionBoundsBuilder: frame_election_provider_support::bounds::ElectionBounds =
        frame_election_provider_support::bounds::ElectionBoundsBuilder::default()
            .voters_count(5_000.into()).targets_count(1_250.into()).build();
}

// pub struct LinearSignedDeposit;
// impl sp_runtime::traits::Convert<usize, Balance> for LinearSignedDeposit {
//     fn convert(n: usize) -> Balance { (n as Balance).saturating_mul(CMN / 100) }
// }









parameter_types! {
    pub const BagsThresholdsParam: &'static [u64] = &[
        10_000, 20_000, 30_000, 50_000, 75_000, 100_000, 150_000, 200_000,
        300_000, 500_000, 750_000, 1_000_000, 1_500_000, 2_000_000, 3_000_000,
        5_000_000, 7_500_000, 10_000_000, 15_000_000, 20_000_000, 30_000_000,
        50_000_000, 75_000_000, 100_000_000, 150_000_000, 200_000_000, 300_000_000,
        500_000_000, 750_000_000, 1_000_000_000, 2_000_000_000, 5_000_000_000,
        10_000_000_000, 20_000_000_000, 50_000_000_000, 100_000_000_000,
    ];
}


// ─── pallet-bags-list ─────────────────────────────────────────────────────────
// Required by staking: Score = VoteWeight = u64 (compatible with staking's VoterList bound)
impl pallet_bags_list::Config for Runtime {
    type RuntimeEvent  = RuntimeEvent;
    type ScoreProvider = Staking;
    type WeightInfo    = pallet_bags_list::weights::SubstrateWeight<Runtime>;
    type BagThresholds = BagsThresholdsParam;
    type Score         = VoteWeight;
}

// ─── pallet-session ───────────────────────────────────────────────────────────
impl pallet_session::Config for Runtime {
    type RuntimeEvent         = RuntimeEvent;
    type ValidatorId          = AccountId;
    type ValidatorIdOf        = pallet_staking::StashOf<Runtime>;
    type ShouldEndSession     = Babe;
    type NextSessionRotation  = Babe;
    type SessionManager       = pallet_session::historical::NoteHistoricalRoot<Self, Staking>;
    type SessionHandler       = <SessionKeys as sp_runtime::traits::OpaqueKeys>::KeyTypeIdProviders;
    type Keys                 = SessionKeys;
    type WeightInfo           = pallet_session::weights::SubstrateWeight<Runtime>;
    type DisablingStrategy    = pallet_session::disabling::UpToLimitDisablingStrategy<3>;
}

impl pallet_session::historical::Config for Runtime {
    type FullIdentification    = pallet_staking::Exposure<AccountId, Balance>;
    type FullIdentificationOf  = pallet_staking::ExposureOf<Runtime>;
}

impl pallet_offences::Config for Runtime {
    type RuntimeEvent         = RuntimeEvent;
    type IdentificationTuple  = pallet_session::historical::IdentificationTuple<Self>;
    type OnOffenceHandler     = Staking;
}

impl pallet_authority_discovery::Config for Runtime {
    type MaxAuthorities = ConstU32<100>;
}

// ─── Custom pallet bridge structs ─────────────────────────────────────────────

pub struct RankedCollectiveBridge;
// V4: RankedCollective is active — bridge reads/writes real pallet storage.
impl pallet_agents::pallet::AgentCollective<AccountId> for RankedCollectiveBridge {
    fn induct(who: &AccountId) -> frame_support::pallet_prelude::DispatchResult {
        // stable2503 added an `emit_event` flag; `true` matches the SDK's own
        // RankedMembers::induct, so inductions stay observable to indexers.
        RankedCollective::do_add_member(who.clone(), true)
            .map_err(|_| frame_support::pallet_prelude::DispatchError::Other("ranked-collective: induct failed"))
    }
    fn promote(who: &AccountId) -> frame_support::pallet_prelude::DispatchResult {
        RankedCollective::do_promote_member(who.clone(), None, true)
            .map_err(|_| frame_support::pallet_prelude::DispatchError::Other("ranked-collective: promote failed"))
    }
    fn rank_of(who: &AccountId) -> Option<u32> {
        // MemberRecord.rank became private at stable2503; rank_of on the
        // RankedMembers trait is the public replacement.
        <RankedCollective as frame_support::traits::RankedMembers>::rank_of(who)
            .map(|r| r as u32)
    }
    fn remove(who: &AccountId) {
        // do_remove_member_from_rank removes the member if their rank <= max_rank.
        // u16::MAX ensures removal at any rank (0, 1, 2, 3, ...).
        let _ = RankedCollective::do_remove_member_from_rank(who, u16::MAX);
    }
}

pub struct IdentityCapabilityBridge;
impl pallet_agents::pallet::IdentityHandler<AccountId> for IdentityCapabilityBridge {
    fn has_identity(who: &AccountId) -> bool {
        pallet_identity::Pallet::<Runtime>::has_identity(who, Default::default())
    }
    fn set_capability(who: &AccountId, capability_id: u32, active: bool)
        -> frame_support::pallet_prelude::DispatchResult
    {
        let _ = (who, capability_id, active);
        Ok(())
    }
    fn agent_has_capability(who: &AccountId, capability_id: u32) -> bool {
        let caps = pallet_agents::AgentCapabilities::<Runtime>::get(who);
        caps.binary_search(&capability_id).is_ok()
    }
}

pub struct OracleCapabilityGate;
impl pallet_oracle::CapabilityChecker<AccountId> for OracleCapabilityGate {
    fn agent_has_capability(who: &AccountId, capability_id: u32) -> bool {
        let caps = pallet_agents::AgentCapabilities::<Runtime>::get(who);
        caps.binary_search(&capability_id).is_ok()
    }
}

pub struct ValidatorCountBridge;
impl pallet_emissions::pallet::ValidatorCountProvider for ValidatorCountBridge {
    fn active_validator_count() -> u32 {
        pallet_staking::Pallet::<Runtime>::active_era()
            .map(|era| pallet_staking::ErasStakersOverview::<Runtime>::iter_prefix(era.index).count() as u32)
            .unwrap_or_else(|| pallet_staking::Validators::<Runtime>::count())
    }
}

pub struct OrchestratorEmissionsImpl;
impl pallet_emissions::pallet::OrchestratorEmissions<Balance> for OrchestratorEmissionsImpl {
    fn compute_weights(multiplier: u32) -> (u128, u32) {
        pallet_orchestrator::Pallet::<Runtime>::compute_era_orchestrator_weights(multiplier)
    }
    fn settle(orch_emission: Balance, orch_weight: u128) {
        if orch_weight > 0 {
            pallet_orchestrator::Pallet::<Runtime>::settle_orchestrator_era(orch_emission, orch_weight);
        }
    }
}

pub struct OrchestratorBridge;
impl pallet_agents::pallet::OrchestratorLookup<AccountId, Balance> for OrchestratorBridge {
    fn get_orchestrator(sub_agent: &AccountId) -> Option<AccountId> {
        pallet_orchestrator::SubAgentToOrchestrator::<Runtime>::get(sub_agent)
    }
    fn add_orchestrator_volume(orchestrator: &AccountId, amount: Balance) {
        pallet_orchestrator::Pallet::<Runtime>::add_orchestrator_volume(orchestrator, amount);
    }
}

/// Verifies an agent holds at least one active (non-empty) vote in any OpenGov
/// referendum class. An agent that has never voted, or whose votes are all
/// empty, fails the check. This prevents record_gov_vote() from being called
/// without genuine participation.
///
/// Carried on a local bridge struct rather than on `ConvictionVoting` directly:
/// both the trait's type parameter (`AccountId`) and the implementing type
/// (`pallet_conviction_voting::Pallet`) are foreign to this crate, so the direct
/// impl violates the orphan rule (E0117). Same shape as the other `*Bridge`
/// structs above. The storage it reads — `pallet_conviction_voting::VotingFor` —
/// is unchanged, which is the load-bearing part of this guard.
pub struct ConvictionVotingBridge;
impl pallet_agents::pallet::GovVoteVerifier<AccountId> for ConvictionVotingBridge {
    fn is_actively_voting(who: &AccountId) -> bool {
        use pallet_conviction_voting::{Voting, VotingFor};
        VotingFor::<Runtime>::iter_prefix(who).any(|(_, voting)| {
            matches!(&voting, Voting::Casting(c) if !c.votes.is_empty())
        })
    }
}

pub struct AutoParamsImpl;
impl pallet_auto_params::pallet::AutoParamsProvider for AutoParamsImpl {
    fn completion_fee_bps() -> u32 { pallet_auto_params::Pallet::<Runtime>::live_completion_fee_bps() }
    fn alpha()              -> u32 { pallet_auto_params::Pallet::<Runtime>::live_alpha() }
    fn beta()               -> u32 { pallet_auto_params::Pallet::<Runtime>::live_beta() }
    fn floor_bps()          -> u32 { pallet_auto_params::Pallet::<Runtime>::live_floor_bps() }
    fn min_score_eligible() -> u32 { pallet_auto_params::Pallet::<Runtime>::live_min_score_eligible() }
    // V4: F-02 fix — run_era_rules is now called every settle_era
    fn run_era_rules(metrics: pallet_auto_params::pallet::EraMetrics) {
        pallet_auto_params::Pallet::<Runtime>::run_era_rules(metrics);
    }
}

pub struct EscrowCompletionFee;
impl frame_support::traits::Get<u32> for EscrowCompletionFee {
    fn get() -> u32 { pallet_auto_params::Pallet::<Runtime>::live_completion_fee_bps() }
}

pub struct OracleCounterBridge;
impl pallet_emissions::pallet::OracleCounters for OracleCounterBridge {
    fn drain_era_counters() -> (u32, u32) {
        pallet_oracle::Pallet::<Runtime>::drain_era_counters()
    }
}

// ─── Custom pallet configs ─────────────────────────────────────────────────────

parameter_types! {
    pub const AgentsMinStake:             Balance = 1_000 * CMN;
    pub const AgentsFullFloorStake:       Balance = 10_000 * CMN;
    pub const AgentsMaxStakePerAgent:     Balance = 1_000_000 * CMN;
    pub const AgentsUnstakeCooldown:      BlockNumber = 7 * DAYS;
    pub const AgentsBaseRegistrationFee:  Balance = 50 * CMN;
    pub const AgentsMaxRegistrationsPerBlock: u32 = 10;
    pub const AgentsMaxAgents:            u32 = 10_000_000;
    pub const AgentsRank3MinCompletions:  u32 = 50;
    pub const AgentsMinRank3OracleScore:  u32 = 1_000;
    pub const AgentsRank3SpanGate:        BlockNumber = 30 * DAYS;
    pub const AgentsMaxVolToStakeRatio:   u32 = 10;
    pub const AgentsHeartbeatGrace:       BlockNumber = HOURS * 18;   // V4: 3 eras grace (was 6h = 1 era — zero margin)
    pub const AgentsHeartbeatDecay:       BlockNumber = DAYS * 90;
    pub const AgentsMaxUriLen:             u32 = 256;
    pub const AgentsMaxNameLen:            u32 = 64;
    pub const AgentsMaxCapabilities:       u32 = 20;
    pub const AgentsMaxDelegationPeriod:   BlockNumber = 90 * DAYS;
    pub const AgentsSlashAppealWindow:     BlockNumber = 10;
    pub const OrchestratorMaxFeeBps:       u32 = 500;
    pub const OrchestratorLinkWindow:      BlockNumber = 7 * DAYS;
}

impl pallet_agents::Config for Runtime {
    type RuntimeEvent             = RuntimeEvent;
    type Currency                 = Balances;
    type MinStake                 = AgentsMinStake;
    type FullFloorStake           = AgentsFullFloorStake;
    type MaxStakePerAgent         = AgentsMaxStakePerAgent;
    type UnstakeCooldown          = AgentsUnstakeCooldown;
    type BaseRegistrationFee      = AgentsBaseRegistrationFee;
    type MaxRegistrationsPerBlock = AgentsMaxRegistrationsPerBlock;
    type MaxAgents                = AgentsMaxAgents;
    type Rank3MinCompletions      = AgentsRank3MinCompletions;
    type MinRank3OracleScore      = AgentsMinRank3OracleScore;
    type Rank3SpanGate            = AgentsRank3SpanGate;
    type MaxVolToStakeRatio       = AgentsMaxVolToStakeRatio;
    type HeartbeatGracePeriod     = AgentsHeartbeatGrace;
    type HeartbeatDecayPeriod     = AgentsHeartbeatDecay;
    type OnAgentRegistered        = Emissions;
    type OnAgentSlashed           = Emissions; // zeros AgentWeightSnapshot after slash
    type OnStakeChanged           = Emissions; // zeros snapshot before stake increase (MasterChef fix)
    type AgentCollective          = RankedCollectiveBridge;
    type OracleScoreGate          = Oracle;
    type GovVoteVerifier          = ConvictionVotingBridge; // verifies active vote before gov credit
    type IdentityHandler          = IdentityCapabilityBridge;
    type OrchestratorLookup       = OrchestratorBridge;
    type MaxUriLen                = AgentsMaxUriLen;
    type MaxNameLen               = AgentsMaxNameLen;
    type MaxCapabilitiesPerAgent  = AgentsMaxCapabilities;
    type MaxDelegationPeriod      = AgentsMaxDelegationPeriod;
    type SlashAppealWindow        = AgentsSlashAppealWindow;
    // V4: F-05 — matches emissions MaxProposalsPerEra so cap is enforced at call time
    type MaxProposalsPerEra       = EmissionsMaxProposalsPerEra;
    // V4: F-07 — slash treasury destination (50% of slash goes here, 50% burned)
    type SlashDestination         = Treasury;
}

parameter_types! {
    pub const EscrowMaxAgreements:     u32 = 10;
    pub const EscrowMaxAgreementSpan:  BlockNumber = 30 * DAYS;
    pub const EscrowMinAmount:         Balance = 10 * CMN;
    pub const EscrowMinDeliveryBlocks: BlockNumber = 10;
    pub const EscrowBuyerRespWindow:   BlockNumber = 3 * DAYS;
    pub const EscrowDisputeTimeout:    BlockNumber = 14 * DAYS;
    pub const EscrowDisputeRespWindow: BlockNumber = 3 * DAYS;
    pub const EscrowDisputeBountyBps:  u32 = 200;
    pub const EscrowMinDisputeBounty:  Balance = CMN;
    pub const EscrowDisputeBurnBps:    u32 = 0;
}
impl pallet_escrow::Config for Runtime {
    type RuntimeEvent           = RuntimeEvent;
    // No Currency type — escrow uses agents' currency via BalanceOf<T> = agents::BalanceOf<T>
    type MaxAgreementsPerPair   = EscrowMaxAgreements;
    type MaxAgreementSpan       = EscrowMaxAgreementSpan;
    type MinAgreementAmount     = EscrowMinAmount;
    type MinDeliveryBlocks      = EscrowMinDeliveryBlocks;
    type BuyerResponseWindow    = EscrowBuyerRespWindow;
    type DisputeTimeoutWindow   = EscrowDisputeTimeout;
    type DisputeResponseWindow  = EscrowDisputeRespWindow;
    type DisputeBountyBps       = EscrowDisputeBountyBps;
    type MinDisputeBounty       = EscrowMinDisputeBounty;
    type DisputeBurnBps         = EscrowDisputeBurnBps;
    type DisputeOracle          = Oracle;
    type DisputeCallback        = Escrow;
    type CompletionFeeProvider  = EscrowCompletionFee;
    // V4: completion fees (25 bps) route to Treasury for governance allocation
    type FeeDestination         = Treasury;
}

parameter_types! {
    pub const OracleMinBounty:          Balance = CMN;
    pub const OracleMaxOpenRequests:    u32 = 1_000;
    pub const OracleMinChallengeWindow: BlockNumber = HOURS;
    pub const OracleMinConsensusThreshold: u8 = 50;
    pub const OracleMaxResponsesPerRequest: u32 = 200;
    pub const OracleMaxBatchSubmissions: u32 = 20;
}
impl pallet_oracle::Config for Runtime {
    type RuntimeEvent              = RuntimeEvent;
    // No Currency type — oracle uses agents' BalanceOf<T>
    type MinOracleBounty           = OracleMinBounty;
    type MaxOpenRequests           = OracleMaxOpenRequests;
    type MinChallengeWindow        = OracleMinChallengeWindow;
    type MinConsensusThreshold     = OracleMinConsensusThreshold;
    type MaxResponsesPerRequest    = OracleMaxResponsesPerRequest;
    type DisputeCallback           = Escrow;
    type CapabilityChecker         = OracleCapabilityGate;
    type MaxBatchSubmissions       = OracleMaxBatchSubmissions;
}

parameter_types! {
    pub const EmissionsSupplyCap:        Balance = SUPPLY_CAP;
    pub const EmissionsInitialPerEra:    Balance = 1_000_000 * CMN;
    pub const EmissionsTargetPerAgent:   Balance = 10_000 * CMN;
    pub const EmissionsFloorPerEra:      Balance = 100_000 * CMN;
    pub const EmissionsEraDuration:      BlockNumber = ERA_BLOCKS;
    pub const EmissionsOracleBonusBps:   u32 = 2_000;
    pub const EmissionsMaxProposalsPerEra: u32 = 20;
    pub const EmissionsUnitVolume:       Balance = 10 * CMN;    // V4: 10 CMN threshold — work_score works for standard agreements
    /// Minimum era escrow volume for floor emission eligibility.
    /// 5 × UnitVolume = 50 CMN. Agents must transact at least 50 CMN per era to
    /// qualify for the floor share. This raises sybil floor farming cost from
    /// 0.025 CMN/era (one 10 CMN deal) to 0.125 CMN/era (five 10 CMN deals or one 50 CMN deal).
    /// Governance can raise this without a runtime upgrade via auto_params if needed.
    pub const EmissionsMinQualifyingVol: Balance = 50 * CMN;
    /// Capital velocity bonus: maximum additional weight for agents that actively
    /// deploy their staked capital in escrow each era.
    /// 3,000 bps = +30% weight when era_vol ≥ stake (full deployment).
    /// An agent cycling 10,000 CMN stake through escrow earns 30% more than an
    /// identical agent that just stakes and heartbeats without doing escrow work.
    pub const EmissionsVelocityBonusBps: u32 = 3_000;
    // V4: EmissionsGenesisBonusBps and EmissionsGenesisBonusEras removed.
    // Replaced by per-agent onboarding_boost in compute_weight_cached.
}
impl pallet_emissions::Config for Runtime {
    type RuntimeEvent              = RuntimeEvent;
    type Currency                  = Balances;
    type SupplyCap                 = EmissionsSupplyCap;
    type InitialEmissionsPerEra    = EmissionsInitialPerEra;
    type TargetEmissionPerAgent    = EmissionsTargetPerAgent;
    type FloorEmissionPerEra       = EmissionsFloorPerEra;
    type EraDuration               = EmissionsEraDuration;
    type MaxBatchClaimSize         = ConstU32<100>;
    type OracleBonusBps            = EmissionsOracleBonusBps;
    type MaxProposalsPerEra        = EmissionsMaxProposalsPerEra;
    type UnitVolume                = EmissionsUnitVolume;
    type VelocityBonusBps          = EmissionsVelocityBonusBps; // +30% weight bonus at full capital deployment
    type MinQualifyingVol          = EmissionsMinQualifyingVol;
    // V4: GenesisAgentBonusBps/Eras removed — replaced by per-agent onboarding_boost
    type AutoParams                = AutoParamsImpl;
    type OracleScoreProvider       = ();
    type OracleCounters            = OracleCounterBridge;
    type MaxEmissionOverrideEras   = ConstU32<10>;
    type ValidatorCountProvider    = ValidatorCountBridge;
    type OrchestratorEmissions     = OrchestratorEmissionsImpl;
    type OrchestratorEmissionMultiplier = ConstU32<5_000>;
}

impl pallet_orchestrator::Config for Runtime {
    type RuntimeEvent                 = RuntimeEvent;
    type MaxSubAgentsPerOrchestrator  = ConstU32<50>;
    type MaxOrchestratorFeeBps        = OrchestratorMaxFeeBps;
    type LinkApprovalWindow           = OrchestratorLinkWindow;
    type MaxPendingProposals          = ConstU32<20>;
    type SupplyCap                    = EmissionsSupplyCap; // shared 100B CMN cap
}

parameter_types! {
    pub const AutoInitialFeeBps:       u32 = 25;   // V4: 0.25% from genesis — treasury income + ring deterrent active
    pub const AutoInitialAlpha:        u32 = 4_000;
    pub const AutoInitialBeta:         u32 = 5_000;
    pub const AutoInitialFloorBps:     u32 = 1_000;
    pub const AutoInitialMinScore:     u32 = 5;
    pub const AutoRingThreshold:       u32 = 3_000;
    pub const AutoOracleLowThreshold:  u32 = 4_000;
    pub const AutoOracleHighThreshold: u32 = 9_000;
    pub const AutoConcentrationHigh:   u32 = 7_000;
    pub const AutoConcentrationLow:    u32 = 5_000;
    pub const AutoMinQuestionsRule:    u32 = 5;
    pub const AutoMinAgentsRule:       u32 = 50;
}
impl pallet_auto_params::Config for Runtime {
    type RuntimeEvent                     = RuntimeEvent;
    type GovernanceOrigin                 = EnsureRoot<AccountId>;
    type InitialCompletionFeeBps          = AutoInitialFeeBps;
    type InitialAlpha                     = AutoInitialAlpha;
    type InitialBeta                      = AutoInitialBeta;
    type InitialFloorBps                  = AutoInitialFloorBps;
    type InitialMinScoreEligible          = AutoInitialMinScore;
    type RingRatioThreshold               = AutoRingThreshold;
    type OracleParticipationLowThreshold  = AutoOracleLowThreshold;
    type OracleParticipationHighThreshold = AutoOracleHighThreshold;
    type ConcentrationHighThreshold       = AutoConcentrationHigh;
    type ConcentrationLowThreshold        = AutoConcentrationLow;
    type MinQuestionsForOracleRule        = AutoMinQuestionsRule;
    type MinAgentsForConcentrationRule    = AutoMinAgentsRule;
}

// ─── construct_runtime ────────────────────────────────────────────────────────
#[frame_support::runtime]
mod runtime {
    #[runtime::runtime]
    #[runtime::derive(RuntimeCall, RuntimeEvent, RuntimeError, RuntimeOrigin,
                      RuntimeFreezeReason, RuntimeHoldReason, RuntimeSlashReason,
                      RuntimeTask, RuntimeViewFunction)]
    pub struct Runtime;

    #[runtime::pallet_index(0)]  pub type System         = frame_system;
    #[runtime::pallet_index(99)] pub type Authorship       = pallet_authorship;
    #[runtime::pallet_index(1)]  pub type Timestamp       = pallet_timestamp;
    #[runtime::pallet_index(35)] pub type Babe            = pallet_babe;
    #[runtime::pallet_index(36)] pub type Grandpa         = pallet_grandpa;
    #[runtime::pallet_index(4)]  pub type Balances         = pallet_balances;
    #[runtime::pallet_index(13)] pub type TransactionPayment = pallet_transaction_payment;
    #[runtime::pallet_index(34)] pub type Staking         = pallet_staking;
    #[runtime::pallet_index(37)] pub type Session         = pallet_session;
    #[runtime::pallet_index(6)]  pub type Historical      = pallet_session::historical;
    // ImOnline removed M1 -- #[runtime::pallet_index(7)] pub type ImOnline = pallet_im_online;
    #[runtime::pallet_index(8)]  pub type AuthorityDiscovery = pallet_authority_discovery;
    #[runtime::pallet_index(9)]  pub type Offences        = pallet_offences;
    #[runtime::pallet_index(10)] pub type VoterList = pallet_bags_list;
    // EPM disabled M1
    // // EPM disabled M1
 // #[runtime::pallet_index(11)] pub type ElectionProviderMultiPhase = pallet_election_provider_multi_phase;
    #[runtime::pallet_index(14)] pub type Vesting          = pallet_vesting;
    // V4: Treasury active — receives slash 50% + completion fees each era.
    #[runtime::pallet_index(15)] pub type Treasury         = pallet_treasury;
    #[runtime::pallet_index(16)] pub type Sudo             = pallet_sudo;
    #[runtime::pallet_index(17)] pub type Utility          = pallet_utility;
    #[runtime::pallet_index(18)] pub type Multisig         = pallet_multisig;
    #[runtime::pallet_index(19)] pub type Scheduler        = pallet_scheduler;
    #[runtime::pallet_index(20)] pub type Preimage          = pallet_preimage;
    #[runtime::pallet_index(21)] pub type Referenda         = pallet_referenda;         // V4: OpenGov
    #[runtime::pallet_index(22)] pub type ConvictionVoting  = pallet_conviction_voting; // V4: OpenGov
    #[runtime::pallet_index(23)] pub type RankedCollective  = pallet_ranked_collective; // V4: active TC
    #[runtime::pallet_index(25)] pub type Identity         = pallet_identity;
    #[runtime::pallet_index(26)] pub type Agents           = pallet_agents;
    #[runtime::pallet_index(27)] pub type Escrow           = pallet_escrow;
    #[runtime::pallet_index(28)] pub type Oracle           = pallet_oracle;
    #[runtime::pallet_index(29)] pub type Emissions        = pallet_emissions;
    #[runtime::pallet_index(30)] pub type AutoParams       = pallet_auto_params;
    #[runtime::pallet_index(31)] pub type Orchestrator     = pallet_orchestrator;
    // V4: governance safety stack
    #[runtime::pallet_index(32)] pub type NominationPools  = pallet_nomination_pools;
    #[runtime::pallet_index(33)] pub type Whitelist        = pallet_whitelist;
    // V4: reassigned to unused indices (34/35/36 are taken by Staking/Babe/Grandpa above).
    #[runtime::pallet_index(38)] pub type SafeMode         = pallet_safe_mode;
    #[runtime::pallet_index(39)] pub type TxPause          = pallet_tx_pause;
    #[runtime::pallet_index(40)] pub type Constitution     = pallet_constitution;
    // V4: Technical Council poll set — pallet-referenda Instance2, carrying the
    // ranked-collective tally. Appended at 41; indices are append-only and 41
    // was previously unused. See ROUND3.md "Governance decisions".
    #[runtime::pallet_index(41)] pub type RankedPolls      = pallet_referenda<Instance2>;
}

// ─── Runtime API implementations ─────────────────────────────────────────────
impl_runtime_apis! {
    impl sp_api::Core<Block> for Runtime {
        fn version() -> RuntimeVersion { VERSION }
        fn execute_block(block: Block) { Executive::execute_block(block); }
        fn initialize_block(header: &<Block as BlockT>::Header)
            -> sp_runtime::ExtrinsicInclusionMode
        {
            Executive::initialize_block(header)
        }
    }

    impl sp_api::Metadata<Block> for Runtime {
        fn metadata() -> OpaqueMetadata {
            OpaqueMetadata::new(Runtime::metadata().into())
        }
        fn metadata_at_version(version: u32) -> Option<OpaqueMetadata> {
            Runtime::metadata_at_version(version)
        }
        fn metadata_versions() -> sp_std::vec::Vec<u32> {
            Runtime::metadata_versions()
        }
    }

    impl sp_block_builder::BlockBuilder<Block> for Runtime {
        fn apply_extrinsic(extrinsic: <Block as BlockT>::Extrinsic) -> ApplyExtrinsicResult {
            Executive::apply_extrinsic(extrinsic)
        }
        fn finalize_block() -> <Block as BlockT>::Header { Executive::finalize_block() }
        fn inherent_extrinsics(data: sp_inherents::InherentData) -> Vec<<Block as BlockT>::Extrinsic> {
            data.create_extrinsics()
        }
        fn check_inherents(
            block: Block,
            data: sp_inherents::InherentData,
        ) -> sp_inherents::CheckInherentsResult {
            data.check_extrinsics(&block)
        }
    }

    impl sp_transaction_pool::runtime_api::TaggedTransactionQueue<Block> for Runtime {
        fn validate_transaction(
            source: TransactionSource,
            tx: <Block as BlockT>::Extrinsic,
            block_hash: <Block as BlockT>::Hash,
        ) -> TransactionValidity {
            Executive::validate_transaction(source, tx, block_hash)
        }
    }

    impl sp_offchain::OffchainWorkerApi<Block> for Runtime {
        fn offchain_worker(header: &<Block as BlockT>::Header) {
            Executive::offchain_worker(header)
        }
    }

    impl sp_session::SessionKeys<Block> for Runtime {
        fn generate_session_keys(seed: Option<Vec<u8>>) -> Vec<u8> {
            SessionKeys::generate(seed)
        }
        fn decode_session_keys(encoded: Vec<u8>) -> Option<Vec<(Vec<u8>, KeyTypeId)>> {
            SessionKeys::decode_into_raw_public_keys(&encoded)
        }
    }

    impl sp_consensus_babe::BabeApi<Block> for Runtime {
        fn configuration() -> sp_consensus_babe::BabeConfiguration {
            let epoch_config = Babe::epoch_config().unwrap_or(BABE_GENESIS_EPOCH_CONFIG);
            sp_consensus_babe::BabeConfiguration {
                slot_duration:       Babe::slot_duration(),
                epoch_length:        EpochDuration::get(),
                c:                   epoch_config.c,
                authorities:         Babe::authorities().to_vec(),
                randomness:          Babe::randomness(),
                allowed_slots:       epoch_config.allowed_slots,
            }
        }
        fn current_epoch_start() -> sp_consensus_babe::Slot { Babe::current_epoch_start() }
        fn current_epoch() -> sp_consensus_babe::Epoch { Babe::current_epoch() }
        fn next_epoch() -> sp_consensus_babe::Epoch { Babe::next_epoch() }
        fn generate_key_ownership_proof(
            _slot: sp_consensus_babe::Slot,
            authority_id: BabeId,
        ) -> Option<sp_consensus_babe::OpaqueKeyOwnershipProof> {
            use sp_runtime::codec::Encode;
            use frame_support::traits::KeyOwnerProofSystem;
            Historical::prove((sp_consensus_babe::KEY_TYPE, authority_id))
                .map(|p: sp_session::MembershipProof| p.encode())
                .map(sp_consensus_babe::OpaqueKeyOwnershipProof::new)
        }
        fn submit_report_equivocation_unsigned_extrinsic(
            equivocation_proof: sp_consensus_babe::EquivocationProof<<Block as BlockT>::Header>,
            key_ownership_proof: sp_consensus_babe::OpaqueKeyOwnershipProof,
        ) -> Option<()> {
            let key_ownership_proof = key_ownership_proof.decode()?;
            Babe::submit_unsigned_equivocation_report(equivocation_proof, key_ownership_proof)
        }
    }

    impl sp_consensus_grandpa::GrandpaApi<Block> for Runtime {
        fn grandpa_authorities() -> sp_consensus_grandpa::AuthorityList {
            Grandpa::grandpa_authorities()
        }
        fn current_set_id() -> sp_consensus_grandpa::SetId {
            Grandpa::current_set_id()
        }
        fn submit_report_equivocation_unsigned_extrinsic(
            _: sp_consensus_grandpa::EquivocationProof<
                <Block as BlockT>::Hash,
                NumberFor<Block>,
            >,
            _: sp_consensus_grandpa::OpaqueKeyOwnershipProof,
        ) -> Option<()> { None }
        fn generate_key_ownership_proof(
            _: sp_consensus_grandpa::SetId,
            _: GrandpaId,
        ) -> Option<sp_consensus_grandpa::OpaqueKeyOwnershipProof> { None }
    }

    impl frame_system_rpc_runtime_api::AccountNonceApi<Block, AccountId, Index> for Runtime {
        fn account_nonce(account: AccountId) -> Index {
            System::account_nonce(account)
        }
    }

    impl pallet_transaction_payment_rpc_runtime_api::TransactionPaymentApi<Block, Balance> for Runtime {
        fn query_info(
            uxt: <Block as BlockT>::Extrinsic,
            len: u32,
        ) -> pallet_transaction_payment_rpc_runtime_api::RuntimeDispatchInfo<Balance> {
            TransactionPayment::query_info(uxt, len)
        }
        fn query_fee_details(
            uxt: <Block as BlockT>::Extrinsic,
            len: u32,
        ) -> pallet_transaction_payment::FeeDetails<Balance> {
            TransactionPayment::query_fee_details(uxt, len)
        }
        fn query_weight_to_fee(weight: Weight) -> Balance {
            TransactionPayment::weight_to_fee(weight)
        }
        fn query_length_to_fee(length: u32) -> Balance {
            TransactionPayment::length_to_fee(length)
        }
    }

    impl crate::scalar_api::ScalarCommonsApi<Block, AccountId, Balance, BlockNumber> for Runtime {
        fn get_agent_info(who: AccountId) -> Option<AgentInfo<AccountId, Balance, BlockNumber>> {
            let stake = pallet_agents::AgentStake::<Runtime>::get(&who)?;
            // MemberRecord.rank became private at stable2503; rank_of on the
            // RankedMembers trait is the public replacement. Semantics are
            // unchanged, including the "not a member reads as rank 0" default.
            let rank = <RankedCollective as frame_support::traits::RankedMembers>::rank_of(&who)
                .map(|r| r as u32)
                .unwrap_or(0u32);
            let completions    = pallet_agents::CompletedAgreements::<Runtime>::get(&who);
            let era_volume     = pallet_agents::EraEscrowVolume::<Runtime>::get(&who);
            let unique_buyers  = pallet_agents::EraUniqueBuyers::<Runtime>::get(&who);
            let last_heartbeat = pallet_agents::LastHeartbeat::<Runtime>::get(&who);
            let heartbeat_mult = pallet_agents::Pallet::<Runtime>::heartbeat_multiplier(&who);
            let capabilities   = pallet_agents::AgentCapabilities::<Runtime>::get(&who).to_vec();
            let orchestrator   = pallet_orchestrator::SubAgentToOrchestrator::<Runtime>::get(&who);
            let (uri, name) = pallet_agents::AgentMetadata::<Runtime>::get(&who)
                .map(|m| (m.uri.to_vec(), m.name.to_vec()))
                .unwrap_or_default();
            let acc    = pallet_emissions::AccRewardPerStake::<Runtime>::get();
            let debt   = pallet_emissions::AgentRewardDebt::<Runtime>::get(&who);
            let weight = pallet_emissions::AgentWeightSnapshot::<Runtime>::get(&who);
            const API_ACC_SCALE: u128 = 1u128 << 64;
            let pending_emissions: Balance = if acc > debt && weight > 0 {
                let delta   = acc.saturating_sub(debt);
                let pending = delta.saturating_mul(weight).checked_div(API_ACC_SCALE).unwrap_or(0);
                let issued: u128 = pallet_balances::Pallet::<Runtime>::total_issuance();
                SUPPLY_CAP.saturating_sub(issued).min(pending)
            } else { 0 };
            Some(AgentInfo {
                stake, rank, completions, era_volume, unique_buyers,
                last_heartbeat, pending_emissions,
                heartbeat_multiplier: heartbeat_mult as u32,
                capabilities, uri, name, orchestrator,
            })
        }

        fn get_era_metrics() -> EraSnapshot<Balance> {
            let orch_count = pallet_orchestrator::OrchestratorRegistration::<Runtime>::iter()
                .count() as u32;
            EraSnapshot {
                era_number:          pallet_agents::EraNumber::<Runtime>::get(),
                active_agents:       pallet_agents::EraActiveSnapshot::<Runtime>::get(),
                ring_count:          pallet_agents::EraRingSnapshot::<Runtime>::get(),
                total_weight:        pallet_emissions::AgentWeightSnapshot::<Runtime>::iter()
                                         .map(|(_, w)| w).sum(),
                last_era_emission:   pallet_emissions::LastEraEmission::<Runtime>::get(),
                completion_fee_bps:  pallet_auto_params::CompletionFeeBps::<Runtime>::get(),
                alpha:               pallet_auto_params::Alpha::<Runtime>::get(),
                beta:                pallet_auto_params::Beta::<Runtime>::get(),
                floor_bps:           pallet_auto_params::FloorBps::<Runtime>::get(),
                active_orchestrators: orch_count,
            }
        }

        fn get_oracle_score(who: AccountId, capability: u32) -> u32 {
            pallet_oracle::OracleScore::<Runtime>::get(&who, capability)
        }

        fn get_pending_emissions(who: AccountId) -> Balance {
            let acc    = pallet_emissions::AccRewardPerStake::<Runtime>::get();
            let debt   = pallet_emissions::AgentRewardDebt::<Runtime>::get(&who);
            let weight = pallet_emissions::AgentWeightSnapshot::<Runtime>::get(&who);
            const PE_ACC_SCALE: u128 = 1u128 << 64;
            if acc > debt && weight > 0 {
                let pending = acc.saturating_sub(debt)
                    .saturating_mul(weight).checked_div(PE_ACC_SCALE).unwrap_or(0);
                let issued: u128 = pallet_balances::Pallet::<Runtime>::total_issuance();
                SUPPLY_CAP.saturating_sub(issued).min(pending)
            } else { 0 }
        }
    }

    impl sp_genesis_builder::GenesisBuilder<Block> for Runtime {
        fn build_state(config: Vec<u8>) -> sp_genesis_builder::Result {
            frame_support::genesis_builder_helper::build_state::<RuntimeGenesisConfig>(config)
        }
        fn get_preset(id: &Option<sp_genesis_builder::PresetId>) -> Option<Vec<u8>> {
            frame_support::genesis_builder_helper::get_preset::<RuntimeGenesisConfig>(
                id, |_| None,
            )
        }
        fn preset_names() -> Vec<sp_genesis_builder::PresetId> { vec![] }
    }
}

pub const BABE_GENESIS_EPOCH_CONFIG: sp_consensus_babe::BabeEpochConfiguration =
    sp_consensus_babe::BabeEpochConfiguration {
        c: (1, 4),
        allowed_slots: sp_consensus_babe::AllowedSlots::PrimaryAndSecondaryPlainSlots,
    };
// pallet-authorship needed for Babe/Grandpa equivocation reports
impl pallet_authorship::Config for Runtime {
    type FindAuthor = pallet_session::FindAccountFromAuthorIndex<Self, Babe>;
    type EventHandler = (Staking,); // ImOnline removed M1
}
