//! # Scalar Commons Runtime v3.0
#![cfg_attr(not(feature = "std"), no_std)]
#![recursion_limit = "256"]

#[cfg(feature = "std")]
include!(concat!(env!("OUT_DIR"), "/wasm_binary.rs"));

// ⚠️  "api" module is renamed to "scalar_api" to avoid conflict with
//     the `api` module generated by impl_runtime_apis!
pub mod scalar_api;

use scalar_api::{AgentInfo, EraSnapshot};

pub mod opaque {
    use super::*;
    pub use sp_runtime::OpaqueExtrinsic as UncheckedExtrinsic;
    pub type Block   = generic::Block<super::Header, UncheckedExtrinsic>;
    pub type BlockId = generic::BlockId<Block>;
}

use frame_support::{
    parameter_types,
    traits::{
        ConstU32, ConstU64, EqualPrivilegeOnly, Everything, WithdrawReasons,
    },
    weights::{constants::WEIGHT_REF_TIME_PER_SECOND, IdentityFee, Weight},
    PalletId,
};
use frame_system::EnsureRoot;
use pallet_grandpa::AuthorityId as GrandpaId;
use sp_api::impl_runtime_apis;
use sp_consensus_babe::AuthorityId as BabeId;
use sp_core::{crypto::KeyTypeId, OpaqueMetadata};
use sp_runtime::{
    generic, impl_opaque_keys,
    traits::{AccountIdLookup, BlakeTwo256, Block as BlockT, IdentifyAccount, NumberFor, Verify},
    transaction_validity::{TransactionSource, TransactionValidity},
    ApplyExtrinsicResult, MultiSignature,
};
use sp_std::prelude::*;
use sp_version::RuntimeVersion;

// ─── Types ───────────────────────────────────────────────────────────────────
pub type AccountId   = <<Signature as Verify>::Signer as IdentifyAccount>::AccountId;
pub type Balance     = u128;
pub type BlockNumber = u32;
pub type Signature   = MultiSignature;
pub type Index       = u32;
pub type Hash        = sp_core::H256;
pub type Block       = generic::Block<Header, UncheckedExtrinsic>;
pub type Header      = generic::Header<BlockNumber, BlakeTwo256>;
pub type SignedBlock  = generic::SignedBlock<Block>;
pub type BlockId     = generic::BlockId<Block>;
pub type SignedExtra = (
    frame_system::CheckNonZeroSender<Runtime>,
    frame_system::CheckSpecVersion<Runtime>,
    frame_system::CheckTxVersion<Runtime>,
    frame_system::CheckGenesis<Runtime>,
    frame_system::CheckEra<Runtime>,
    frame_system::CheckNonce<Runtime>,
    frame_system::CheckWeight<Runtime>,
    pallet_transaction_payment::ChargeTransactionPayment<Runtime>,
);
pub type UncheckedExtrinsic =
    generic::UncheckedExtrinsic<Address, RuntimeCall, Signature, SignedExtra>;
pub type Address = sp_runtime::MultiAddress<AccountId, ()>;
pub type Executive = frame_executive::Executive<
    Runtime, Block, frame_system::ChainContext<Runtime>, Runtime, AllPalletsWithSystem,
>;

// ─── Token constants ─────────────────────────────────────────────────────────
pub const CMN:          Balance = 1_000_000_000_000;
pub const SUPPLY_CAP:   Balance = 100_000_000_000 * CMN;
pub const GENESIS_MINT: Balance = 18_000_000_000  * CMN;

/// The on-chain account ID for the Treasury pallet.
/// Used in chain_spec genesis config to pre-fund the Treasury.
/// Derivation: PalletId(*b"sc/trsry").into_account_truncating()
pub fn treasury_account_id() -> AccountId {
    use frame_support::PalletId;
    use sp_runtime::traits::AccountIdConversion;
    PalletId(*b"sc/trsry").into_account_truncating()
}

// ─── Block/time constants ─────────────────────────────────────────────────────
pub const SECS_PER_BLOCK:    u64 = 6;
pub const MILLISECS_PER_BLOCK: u64 = SECS_PER_BLOCK * 1_000;
pub const SLOT_DURATION:     u64 = MILLISECS_PER_BLOCK;
pub const MINUTES: BlockNumber = 60 / (SECS_PER_BLOCK as BlockNumber);
pub const HOURS:   BlockNumber = MINUTES * 60;
pub const DAYS:    BlockNumber = HOURS * 24;
pub const ERA_BLOCKS: BlockNumber = HOURS * 6;

// ─── Version ─────────────────────────────────────────────────────────────────
#[sp_version::runtime_version]
pub const VERSION: RuntimeVersion = RuntimeVersion {
    spec_name:         ::sp_runtime::create_runtime_str!("scalar-commons"),
    impl_name:         ::sp_runtime::create_runtime_str!("scalar-commons"),
    authoring_version: 1,
    spec_version:      300,
    impl_version:      0,
    apis:              RUNTIME_API_VERSIONS,
    transaction_version: 1,
    system_version:    1,
};

// ─── Session keys ─────────────────────────────────────────────────────────────
impl_opaque_keys! {
    pub struct SessionKeys {
        pub babe:                Babe,
        pub grandpa:             Grandpa,
        pub authority_discovery: AuthorityDiscovery,
    }
}

// ─── Weight constants ─────────────────────────────────────────────────────────
const NORMAL_DISPATCH_RATIO:  sp_runtime::Perbill = sp_runtime::Perbill::from_percent(75);
const MAXIMUM_BLOCK_WEIGHT:   Weight = Weight::from_parts(2 * WEIGHT_REF_TIME_PER_SECOND, u64::MAX);

parameter_types! {
    pub const Version: RuntimeVersion = VERSION;
    pub BlockWeights: frame_system::limits::BlockWeights =
        frame_system::limits::BlockWeights::with_sensible_defaults(
            MAXIMUM_BLOCK_WEIGHT, NORMAL_DISPATCH_RATIO,
        );
    pub BlockLength: frame_system::limits::BlockLength =
        frame_system::limits::BlockLength::max_with_normal_ratio(
            5 * 1024 * 1024, NORMAL_DISPATCH_RATIO,
        );
    pub const SS58Prefix: u8 = 42;
}

// ─── frame_system ─────────────────────────────────────────────────────────────
/// V4: BaseCallFilter wraps the constitution check.
/// Blocks any call that would breach the supply cap invariant.
/// All other calls pass through to their respective pallets.
/// Per-call invariants (self-deal, cooldown, burn) are enforced within individual pallets.
pub struct ConstitutionalFilter;
impl frame_support::traits::Contains<RuntimeCall> for ConstitutionalFilter {
    fn contains(_call: &RuntimeCall) -> bool {
        // Invariant 1: supply cap. Checked on every extrinsic dispatch.
        // Returns false to BLOCK the call if cap is already breached.
        pallet_constitution::Pallet::<Runtime>::base_call_allowed()
    }
}

impl frame_system::Config for Runtime {
    type BaseCallFilter         = ConstitutionalFilter;
    type BlockWeights           = BlockWeights;
    type BlockLength            = BlockLength;
    type RuntimeOrigin          = RuntimeOrigin;
    type RuntimeCall            = RuntimeCall;
    type RuntimeTask            = ();
    type Nonce                  = Index;
    type Hash                   = Hash;
    type Hashing                = BlakeTwo256;
    type AccountId              = AccountId;
    type Lookup                 = AccountIdLookup<AccountId, ()>;
    type Block                  = Block;
    type RuntimeEvent           = RuntimeEvent;
    type BlockHashCount         = ConstU32<2400>;
    type DbWeight               = frame_support::weights::constants::RocksDbWeight;
    type Version                = Version;
    type PalletInfo             = PalletInfo;
    type AccountData            = pallet_balances::AccountData<Balance>;
    type OnNewAccount           = ();
    type OnKilledAccount        = ();
    type SystemWeightInfo       = frame_system::weights::SubstrateWeight<Runtime>;
    type SS58Prefix             = SS58Prefix;
    type OnSetCode              = ();
    type MaxConsumers           = ConstU32<16>;
    type ExtensionsWeightInfo   = ();
    type SingleBlockMigrations  = ();
    type MultiBlockMigrator     = ();
    type PreInherents           = ();
    type PostInherents          = ();
    type PostTransactions       = ();
}

// ─── pallet-timestamp ─────────────────────────────────────────────────────────
parameter_types! {
    pub const MinimumPeriod: u64 = SLOT_DURATION / 2;
}
impl pallet_timestamp::Config for Runtime {
    type Moment       = u64;
    type OnTimestampSet = Babe;
    type MinimumPeriod = MinimumPeriod;
    type WeightInfo   = pallet_timestamp::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-babe ──────────────────────────────────────────────────────────────
parameter_types! {
    pub const EpochDuration: u64 = ERA_BLOCKS as u64 / 2;
    pub const ExpectedBlockTime: u64 = MILLISECS_PER_BLOCK;
    pub const ReportLongevity: u64 = 168;
}
impl pallet_babe::Config for Runtime {
    type EpochDuration            = EpochDuration;
    type ExpectedBlockTime        = ExpectedBlockTime;
    type EpochChangeTrigger       = pallet_babe::ExternalTrigger;
    type DisabledValidators       = Session;
    type WeightInfo               = ();
    type MaxAuthorities           = ConstU32<100>;
    type MaxNominators            = ConstU32<512>;
    type KeyOwnerProof            = sp_session::MembershipProof;
    type EquivocationReportSystem = (); // M1: no equivocation slashing
}

// ─── pallet-grandpa ───────────────────────────────────────────────────────────
impl pallet_grandpa::Config for Runtime {
    type RuntimeEvent             = RuntimeEvent;
    type WeightInfo               = ();
    type MaxAuthorities           = ConstU32<100>;
    type MaxNominators            = ConstU32<512>;
    type MaxSetIdSessionEntries   = ConstU64<168>;
    type KeyOwnerProof            = sp_session::MembershipProof;
    type EquivocationReportSystem = (); // M1: no equivocation slashing
}

// ─── pallet-balances ──────────────────────────────────────────────────────────
parameter_types! {
    pub const ExistentialDeposit: Balance = CMN / 100;
    pub const MaxLocks: u32 = 50;
}
impl pallet_balances::Config for Runtime {
    type MaxLocks             = MaxLocks;
    type MaxReserves          = ConstU32<50>;
    type ReserveIdentifier    = [u8; 8];
    type Balance              = Balance;
    type RuntimeEvent         = RuntimeEvent;
    type DustRemoval          = ();
    type ExistentialDeposit   = ExistentialDeposit;
    type AccountStore         = System;
    type WeightInfo           = pallet_balances::weights::SubstrateWeight<Runtime>;
    type FreezeIdentifier     = RuntimeFreezeReason;
    type MaxFreezes           = ConstU32<8>;
    type RuntimeHoldReason    = RuntimeHoldReason;
    type RuntimeFreezeReason  = RuntimeFreezeReason;
    type DoneSlashHandler     = ();
}

// ─── pallet-transaction-payment ───────────────────────────────────────────────
parameter_types! {
    pub const TransactionByteFee: Balance = CMN / 1_000;
    pub const OperationalFeeMultiplier: u8 = 5;
}
impl pallet_transaction_payment::Config for Runtime {
    type RuntimeEvent             = RuntimeEvent;
    type OnChargeTransaction      = pallet_transaction_payment::FungibleAdapter<Balances, ()>;
    type OperationalFeeMultiplier = OperationalFeeMultiplier;
    type WeightToFee              = IdentityFee<Balance>;
    type LengthToFee              = IdentityFee<Balance>;
    type FeeMultiplierUpdate      = ();
    type WeightInfo               = ();
}

// ─── pallet-sudo ──────────────────────────────────────────────────────────────
impl pallet_sudo::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type RuntimeCall  = RuntimeCall;
    type WeightInfo   = pallet_sudo::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-utility ───────────────────────────────────────────────────────────
impl pallet_utility::Config for Runtime {
    type RuntimeEvent   = RuntimeEvent;
    type RuntimeCall    = RuntimeCall;
    type PalletsOrigin  = OriginCaller;
    type WeightInfo     = pallet_utility::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-multisig ──────────────────────────────────────────────────────────
parameter_types! {
    pub const DepositBase:   Balance = CMN;
    pub const DepositFactor: Balance = CMN / 10;
}
impl pallet_multisig::Config for Runtime {
    type RuntimeEvent       = RuntimeEvent;
    type RuntimeCall        = RuntimeCall;
    type Currency           = Balances;
    type DepositBase        = DepositBase;
    type DepositFactor      = DepositFactor;
    type MaxSignatories     = ConstU32<20>;
    type WeightInfo         = pallet_multisig::weights::SubstrateWeight<Runtime>;
    type BlockNumberProvider = System;
}

// ─── pallet-vesting ───────────────────────────────────────────────────────────
parameter_types! {
    pub const MinVestedTransfer: Balance = 1_000 * CMN;
    pub UnvestedFundsAllowedWithdrawReasons: WithdrawReasons =
        WithdrawReasons::except(WithdrawReasons::TRANSFER);
}
impl pallet_vesting::Config for Runtime {
    type RuntimeEvent         = RuntimeEvent;
    type Currency             = Balances;
    type BlockNumberToBalance = sp_runtime::traits::ConvertInto;
    type MinVestedTransfer    = MinVestedTransfer;
    type WeightInfo           = pallet_vesting::weights::SubstrateWeight<Runtime>;
    type UnvestedFundsAllowedWithdrawReasons = UnvestedFundsAllowedWithdrawReasons;
    type BlockNumberProvider  = System;
    const MAX_VESTING_SCHEDULES: u32 = 28;
}

// ─── pallet-treasury ──────────────────────────────────────────────────────────
parameter_types! {
    pub const SpendPeriod:     BlockNumber = 30 * DAYS;
    pub const TreasuryPalletId: PalletId = PalletId(*b"sc/trsry");
    pub const PayoutPeriod:    BlockNumber = 30 * DAYS;
}

/// EnsureOrigin returning the max Balance as Success (for SpendOrigin).
pub struct EnsureRootWithMaxBalance;
impl frame_support::traits::EnsureOrigin<RuntimeOrigin> for EnsureRootWithMaxBalance {
    type Success = Balance;
    fn try_origin(o: RuntimeOrigin) -> Result<Balance, RuntimeOrigin> {
        EnsureRoot::<AccountId>::try_origin(o).map(|_| Balance::MAX)
    }
    #[cfg(feature = "runtime-benchmarks")]
    fn try_successful_origin() -> Result<RuntimeOrigin, ()> { Ok(RuntimeOrigin::root()) }
}

/// Identity balance converter (native-only treasury, AssetKind = ()).
pub struct NativeBalanceConverter;
impl frame_support::traits::tokens::ConversionFromAssetBalance<Balance, (), Balance>
    for NativeBalanceConverter
{
    type Error = sp_runtime::DispatchError;
    fn from_asset_balance(balance: Balance, _: ()) -> Result<Balance, Self::Error> { Ok(balance) }
    #[cfg(feature = "runtime-benchmarks")]
    fn ensure_successful(_: &()) {}
}

// Treasury — V4: active. Receives 50% of slashes and completion fees.
parameter_types! {
    pub const ProposalBond:        sp_runtime::Permill = sp_runtime::Permill::from_percent(5);
    pub const ProposalBondMinimum: Balance = 100 * CMN;
    pub const ProposalBondMaximum: Balance = 10_000 * CMN;
    pub TreasuryAccount: AccountId = TreasuryPalletId::get().into_account_truncating();
}
impl pallet_treasury::Config for Runtime {
    type PalletId              = TreasuryPalletId;
    type Currency              = Balances;
    type RejectOrigin          = EnsureRoot<AccountId>;
    type RuntimeEvent          = RuntimeEvent;
    type SpendPeriod           = SpendPeriod;
    type Burn                  = ();
    type BurnDestination       = ();
    type SpendFunds            = ();
    type WeightInfo            = pallet_treasury::weights::SubstrateWeight<Runtime>;
    type MaxApprovals          = ConstU32<100>;
    // V4: EnsureRootWithMaxBalance allows Root (sudo during bootstrap) and
    // Track 2 governance (post-day-14) to spend from Treasury without limit.
    // The Balance::MAX cap means governance decides the actual amount per proposal.
    type SpendOrigin           = EnsureRootWithMaxBalance;
    type AssetKind             = ();
    type Beneficiary           = AccountId;
    type BeneficiaryLookup     = frame_support::traits::IdentityLookup<AccountId>;
    type Paymaster             = frame_support::traits::tokens::pay::PayFromAccount<Balances, TreasuryAccount>;
    type BalanceConverter      = frame_support::traits::tokens::UnityAssetBalanceConversion;
    type PayoutPeriod          = PayoutPeriod;
    #[cfg(feature = "runtime-benchmarks")]
    type BenchmarkHelper       = ();
}

// ─── pallet-scheduler ─────────────────────────────────────────────────────────
parameter_types! {
    pub MaximumSchedulerWeight: Weight =
        sp_runtime::Perbill::from_percent(80) * BlockWeights::get().max_block;
}
impl pallet_scheduler::Config for Runtime {
    type RuntimeEvent         = RuntimeEvent;
    type RuntimeOrigin        = RuntimeOrigin;
    type PalletsOrigin        = OriginCaller;
    type RuntimeCall          = RuntimeCall;
    type MaximumWeight        = MaximumSchedulerWeight;
    type ScheduleOrigin       = EnsureRoot<AccountId>;
    type MaxScheduledPerBlock = ConstU32<50>;
    type WeightInfo           = pallet_scheduler::weights::SubstrateWeight<Runtime>;
    type OriginPrivilegeCmp   = EqualPrivilegeOnly;
    type Preimages            = Preimage;
    type BlockNumberProvider  = System;
}

// ─── pallet-preimage ──────────────────────────────────────────────────────────
parameter_types! {
    pub const PreimageBaseDeposit: Balance = CMN;
    pub const PreimageByteDeposit: Balance = CMN / 1_000;
    pub const PreimageHoldReason: RuntimeHoldReason =
        RuntimeHoldReason::Preimage(pallet_preimage::HoldReason::Preimage);
}
impl pallet_preimage::Config for Runtime {
    type RuntimeEvent  = RuntimeEvent;
    type Currency      = Balances;
    type ManagerOrigin = EnsureRoot<AccountId>;
    type Consideration = frame_support::traits::fungible::HoldConsideration<
        AccountId,
        Balances,
        PreimageHoldReason,
        frame_support::traits::LinearStoragePrice<PreimageBaseDeposit, PreimageByteDeposit, Balance>,
    >;
    type WeightInfo = pallet_preimage::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-ranked-collective ─────────────────────────────────────────────────
// M1: rank management only — no governance voting (Polls = ()).
// OpenGov will be wired in M2.

pub struct EnsureRootWithRank;
impl frame_support::traits::EnsureOrigin<RuntimeOrigin> for EnsureRootWithRank {
    type Success = u16;
    fn try_origin(o: RuntimeOrigin) -> Result<u16, RuntimeOrigin> {
        EnsureRoot::<AccountId>::try_origin(o).map(|_| u16::MAX)
    }
    #[cfg(feature = "runtime-benchmarks")]
    fn try_successful_origin() -> Result<RuntimeOrigin, ()> { Ok(RuntimeOrigin::root()) }
}

// V4: RankedCollective is active — Technical Council from rank-3 agents.
// Polls wired to pallet_referenda so TC votes accelerate governance tracks.
impl pallet_ranked_collective::Config for Runtime {
    type WeightInfo          = pallet_ranked_collective::weights::SubstrateWeight<Self>;
    type RuntimeEvent        = RuntimeEvent;
    type AddOrigin           = EnsureRoot<AccountId>;
    type PromoteOrigin       = EnsureRootWithRank;
    type DemoteOrigin        = EnsureRootWithRank;
    type RemoveOrigin        = EnsureRootWithRank;
    type ExchangeOrigin      = EnsureRoot<AccountId>;
    type Polls               = Referenda;
    type MinRankOfClass      = sp_runtime::traits::ConvertInto;
    type MemberSwappedHandler = ();
    type VoteWeight          = pallet_ranked_collective::Geometric;
    type MaxMemberCount      = ();
    #[cfg(feature = "runtime-benchmarks")]
    type BenchmarkSetup = ();
}

// ─── pallet-referenda (OpenGov) ───────────────────────────────────────────────
// V4: Active at genesis. Tracks: 0=agents(24h), 1=network(7d), 2=root(20d).
parameter_types! {
    pub const SubmissionDeposit:  Balance     = 100 * CMN;
    pub const UndecidingTimeout:  BlockNumber = 14 * DAYS;
}
impl pallet_referenda::Config for Runtime {
    type WeightInfo        = pallet_referenda::weights::SubstrateWeight<Self>;
    type RuntimeCall       = RuntimeCall;
    type RuntimeEvent      = RuntimeEvent;
    type Scheduler         = Scheduler;
    type Currency          = Balances;
    type SubmitOrigin      = frame_system::EnsureSigned<AccountId>;
    type CancelOrigin      = governance::origins::AgentsOrRoot;
    type KillOrigin        = EnsureRoot<AccountId>;
    type Slash             = Treasury;
    type Votes             = pallet_conviction_voting::VotesOf<Runtime>;
    type Tally             = pallet_conviction_voting::TallyOf<Runtime>;
    type SubmissionDeposit = SubmissionDeposit;
    type MaxQueued         = ConstU32<100>;
    type UndecidingTimeout = UndecidingTimeout;
    type AlarmInterval     = ConstU32<1>;
    type Tracks            = governance::tracks::TracksInfo;
    type Preimages         = Preimage;
}

// ─── pallet-conviction-voting ─────────────────────────────────────────────────
impl pallet_conviction_voting::Config for Runtime {
    type WeightInfo        = pallet_conviction_voting::weights::SubstrateWeight<Self>;
    type RuntimeEvent      = RuntimeEvent;
    type Currency          = Balances;
    type VoteLockingPeriod = ConstU32<{ ERA_BLOCKS }>;
    type MaxVotes          = ConstU32<512>;
    type MaxTurnout        = frame_support::traits::TotalIssuanceOf<Balances, AccountId>;
    type Polls             = Referenda;
}

// ─── pallet-identity ──────────────────────────────────────────────────────────
parameter_types! {
    pub const BasicDeposit:   Balance = 10 * CMN;
    pub const ByteDeposit:    Balance = CMN / 10;
    pub const SubAccountDeposit: Balance = 2 * CMN;
    pub const MaxSubAccounts: u32 = 100;
    pub const MaxAdditionalFields: u32 = 20;
    pub const MaxRegistrars:  u32 = 20;
    pub const UsernameDeposit: Balance = CMN;
    pub const UsernameGracePeriod: BlockNumber = 30 * DAYS;
}
impl pallet_identity::Config for Runtime {
    type RuntimeEvent            = RuntimeEvent;
    type Currency                = Balances;
    type BasicDeposit            = BasicDeposit;
    type ByteDeposit             = ByteDeposit;
    type SubAccountDeposit       = SubAccountDeposit;
    type MaxSubAccounts          = MaxSubAccounts;
    type IdentityInformation     = pallet_identity::legacy::IdentityInfo<MaxAdditionalFields>;
    type MaxRegistrars           = MaxRegistrars;
    type Slashed                 = ();
    type ForceOrigin             = EnsureRoot<AccountId>;
    type RegistrarOrigin         = EnsureRoot<AccountId>;
    type OffchainSignature       = Signature;
    type SigningPublicKey        = <Signature as sp_runtime::traits::Verify>::Signer;
    type UsernameAuthorityOrigin = EnsureRoot<AccountId>;
    type PendingUsernameExpiration = ConstU32<{ 7 * DAYS }>;
    type MaxSuffixLength         = ConstU32<7>;
    type MaxUsernameLength       = ConstU32<32>;
    type WeightInfo              = pallet_identity::weights::SubstrateWeight<Runtime>;
    type UsernameDeposit         = UsernameDeposit;
    type UsernameGracePeriod     = UsernameGracePeriod;
}

// ImOnline removed M1

// ─── pallet-whitelist (V4: TC fast-track — enables 6h governance path) ───────
// WhitelistOrigin: Either Root (sudo during 14-day bootstrap) OR rank-2+ agents (TC post-day-14).
// After sudo removal, only ranked_collective members at rank 2+ can whitelist calls.
// DispatchWhitelistedOrigin: same — only TC can dispatch a whitelisted call.
impl pallet_whitelist::Config for Runtime {
    type RuntimeEvent              = RuntimeEvent;
    type WhitelistOrigin           = governance::origins::AgentsOrRoot;
    type DispatchWhitelistedOrigin = governance::origins::AgentsOrRoot;
    type Preimages                 = Preimage;
    type WeightInfo                = pallet_whitelist::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-safe-mode (V4: TC emergency circuit breaker — max 4h pause) ──────
parameter_types! {
    pub const SafeModeMaxDuration: BlockNumber = HOURS * 4;  // TC can pause chain ≤ 4 hours
}
/// Calls permitted through SafeMode when the chain is paused.
/// Only governance calls pass — agents can still vote to exit safe mode.
pub struct SafeModeWhitelistedCalls;
impl frame_support::traits::Contains<RuntimeCall> for SafeModeWhitelistedCalls {
    fn contains(call: &RuntimeCall) -> bool {
        matches!(call,
            // Governance must stay live so TC can act and resolve the emergency
            RuntimeCall::Referenda(_)        |
            RuntimeCall::ConvictionVoting(_) |
            RuntimeCall::Whitelist(_)        |
            RuntimeCall::SafeMode(_)         |
            // TC (ranked-collective) must be able to vote to exit SafeMode
            // post-sudo-removal — otherwise there is a deadlock where SafeMode
            // blocks the only actors who can exit it.
            RuntimeCall::RankedCollective(_) |
            // Sudo must stay live during the 14-day bootstrap window
            RuntimeCall::Sudo(_)             |
            // System utility calls (timestamp inherent, etc.) must pass
            RuntimeCall::Timestamp(_)        |
            RuntimeCall::System(_)
        )
    }
}
impl pallet_safe_mode::Config for Runtime {
    type RuntimeEvent          = RuntimeEvent;
    type Currency              = Balances;
    type RuntimeHoldReason     = RuntimeHoldReason;
    type WhitelistedCalls      = SafeModeWhitelistedCalls;
    type EnterOrigin           = EnsureRoot<AccountId>;  // TC multi-sig → root
    type ForceEnterOrigin      = EnsureRoot<AccountId>;
    type ExitOrigin            = EnsureRoot<AccountId>;
    type ForceExitOrigin       = EnsureRoot<AccountId>;
    type EnteredDeposit        = ConstU128<0>;
    type ExtendDeposit         = ConstU128<0>;
    type MaxDuration           = SafeModeMaxDuration;
    type WeightInfo            = pallet_safe_mode::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-tx-pause (V4: surgical pause of specific extrinsics) ──────────────
impl pallet_tx_pause::Config for Runtime {
    type RuntimeEvent          = RuntimeEvent;
    type RuntimeCall           = RuntimeCall;
    type PauseOrigin           = EnsureRoot<AccountId>;  // TC → root
    type UnpauseOrigin         = EnsureRoot<AccountId>;
    type FullNameOf            = pallet_tx_pause::RuntimeCallNameOf<Runtime>;
    type MaxNameLen            = ConstU32<256>;
    type WeightInfo            = pallet_tx_pause::weights::SubstrateWeight<Runtime>;
}

// ─── pallet-constitution (V4: 6 invariants as pre-dispatch hooks) ─────────────
parameter_types! {
    // 1% of supply cap = 1,000,000,000 CMN warning buffer
    pub const ConstitutionCapWarning: Balance = 1_000_000_000 * CMN;
    // Invariant 3: unstake cooldown floor — governance cannot go below 7 days
    pub const ConstitutionMinCooldown: BlockNumber = 7 * DAYS;
    // Invariant 4: oracle challenge window floor — governance cannot go below 1 hour
    pub const ConstitutionMinChallengeWindow: BlockNumber = HOURS;
    // Invariant 5: registration burn floor — Sybil cost cannot be removed
    pub const ConstitutionMinBurn: Balance = 10 * CMN;
}
impl pallet_constitution::Config for Runtime {
    type RuntimeEvent          = RuntimeEvent;
    type Currency              = Balances;
    type SupplyCap             = EmissionsSupplyCap;
    type MinUnstakeCooldown    = ConstitutionMinCooldown;
    type MinChallengeWindow    = ConstitutionMinChallengeWindow;
    type MinRegistrationBurn   = ConstitutionMinBurn;
    type CapWarningBuffer      = ConstitutionCapWarning;
}

// ─── pallet-nomination-pools (V4: active — any agent can pool-stake) ─────────
parameter_types! {
    pub const NomPoolsMinJoinBond:   Balance = 100 * CMN;
    pub const NomPoolsMinCreateBond: Balance = 5_000 * CMN;
    pub const NomPoolsMaxPools:      u32     = 1_000;
    pub const NomPoolsMaxMembers:    u32     = 1_000_000;
    pub const NomPoolsPalletId:      PalletId = PalletId(*b"nompools");
}
// Conversion helpers for nomination pools Balance ↔ U256
pub struct BalanceToU256;
impl sp_runtime::traits::Convert<Balance, sp_core::U256> for BalanceToU256 {
    fn convert(b: Balance) -> sp_core::U256 { sp_core::U256::from(b) }
}
pub struct U256ToBalance;
impl sp_runtime::traits::Convert<sp_core::U256, Balance> for U256ToBalance {
    fn convert(u: sp_core::U256) -> Balance {
        u.try_into().unwrap_or(Balance::MAX)
    }
}
impl pallet_nomination_pools::Config for Runtime {
    type RuntimeEvent           = RuntimeEvent;
    type WeightInfo             = pallet_nomination_pools::weights::SubstrateWeight<Runtime>;
    type Currency               = Balances;
    type RuntimeFreezeReason    = RuntimeFreezeReason;
    type RewardCounter          = sp_runtime::FixedU128;
    type BalanceToU256          = BalanceToU256;
    type U256ToBalance          = U256ToBalance;
    type StakeAdapter           = pallet_nomination_pools::adapter::TransferStake<Self, Staking>;
    type PostUnbondingPoolsWindow = ConstU32<4>;
    type MaxMetadataLen         = ConstU32<256>;
    type MaxUnbonding           = ConstU32<8>;
    type PalletId               = NomPoolsPalletId;
    type MaxPointsToBalance     = frame_support::traits::ConstU8<10>;
    type AdminOrigin            = EnsureRoot<AccountId>;
}


parameter_types! {
    pub const SessionsPerEra:    sp_staking::SessionIndex = 6;
    pub const BondingDuration:   sp_staking::EraIndex     = 28;
    pub const SlashDeferDuration: sp_staking::EraIndex    = 27;
    pub const MaxExposurePageSize: u32 = 64;
}
pallet_staking_reward_curve::build! {
    const REWARD_CURVE: sp_runtime::curve::PiecewiseLinear<'static> = curve!(
        min_inflation: 0_025_000,
        max_inflation: 0_100_000,
        ideal_stake:   0_500_000,
        falloff:       0_050_000,
        max_piece_count: 40,
        test_precision:  0_005_000,
    );
}
parameter_types! {
    pub const RewardCurve: &'static sp_runtime::curve::PiecewiseLinear<'static> = &REWARD_CURVE;
}

pub struct ScalarStakingBenchmarkConfig;
impl pallet_staking::BenchmarkingConfig for ScalarStakingBenchmarkConfig {
    type MaxValidators = ConstU32<1000>;
    type MaxNominators = ConstU32<1000>;
}

impl pallet_staking::Config for Runtime {
    type Currency                          = Balances;
    type CurrencyBalance                   = Balance;
    type UnixTime                          = Timestamp;
    type CurrencyToVote                    = sp_staking::currency_to_vote::U128CurrencyToVote;
    type RewardRemainder                   = Treasury; // leftover staking inflation → Treasury
    type RuntimeEvent                      = RuntimeEvent;
    type Slash                             = Treasury; // equivocation slashes → Treasury
    type Reward                            = ();
    type SessionsPerEra                    = SessionsPerEra;
    type BondingDuration                   = BondingDuration;
    type SlashDeferDuration                = SlashDeferDuration;
    type AdminOrigin                       = EnsureRoot<AccountId>;
    type SessionInterface                  = Self;
    type EraPayout                         = pallet_staking::ConvertCurve<RewardCurve>;
    type NextNewSession                    = Session;
    type HistoryDepth                      = ConstU32<84>;
    type MaxExposurePageSize               = MaxExposurePageSize;
    type ElectionProvider                  = onchain::OnChainExecution<OnChainSeqPhragmen>;
    type GenesisElectionProvider           = onchain::OnChainExecution<OnChainSeqPhragmen>;
    type VoterList                         = VoterList; // pallet_bags_list — Score=VoteWeight=u64 ✓
    type NominationsQuota                  = pallet_staking::FixedNominationsQuota<16>;
    type TargetList                        = pallet_staking::UseValidatorsMap<Self>;
    type MaxUnlockingChunks                = ConstU32<32>;
    type BenchmarkingConfig                = ScalarStakingBenchmarkConfig;
    type WeightInfo                        = pallet_staking::weights::SubstrateWeight<Runtime>;
    type OldCurrency                       = Balances;
    type RuntimeHoldReason                 = RuntimeHoldReason;
    type MaxControllersInDeprecationBatch  = ConstU32<100>;
    type EventListeners                    = ();
    type Filter                            = ();
}

// ─── NPoS election setup ─────────────────────────────────────────────────────
use frame_election_provider_support::{onchain, SequentialPhragmen, VoteWeight};

pub struct OnChainSeqPhragmen;
impl onchain::Config for OnChainSeqPhragmen {
    type System      = Runtime;
    type Solver      = SequentialPhragmen<AccountId, sp_runtime::Perbill>;
    type DataProvider = Staking;
    type WeightInfo  = frame_election_provider_support::weights::SubstrateWeight<Runtime>;
    type MaxWinners  = ConstU32<100>;
    type Bounds      = ElectionBoundsBuilder;
}

parameter_types! {
    pub ElectionBoundsBuilder: frame_election_provider_support::bounds::ElectionBounds =
        frame_election_provider_support::bounds::ElectionBoundsBuilder::default()
            .voters_count(5_000.into()).targets_count(1_250.into()).build();
}

// pub struct LinearSignedDeposit;
// impl sp_runtime::traits::Convert<usize, Balance> for LinearSignedDeposit {
//     fn convert(n: usize) -> Balance { (n as Balance).saturating_mul(CMN / 100) }
// }









parameter_types! {
    pub const BagsThresholdsParam: &'static [u64] = &[
        10_000, 20_000, 30_000, 50_000, 75_000, 100_000, 150_000, 200_000,
        300_000, 500_000, 750_000, 1_000_000, 1_500_000, 2_000_000, 3_000_000,
        5_000_000, 7_500_000, 10_000_000, 15_000_000, 20_000_000, 30_000_000,
        50_000_000, 75_000_000, 100_000_000, 150_000_000, 200_000_000, 300_000_000,
        500_000_000, 750_000_000, 1_000_000_000, 2_000_000_000, 5_000_000_000,
        10_000_000_000, 20_000_000_000, 50_000_000_000, 100_000_000_000,
    ];
}


// ─── pallet-bags-list ─────────────────────────────────────────────────────────
// Required by staking: Score = VoteWeight = u64 (compatible with staking's VoterList bound)
impl pallet_bags_list::Config for Runtime {
    type RuntimeEvent  = RuntimeEvent;
    type ScoreProvider = Staking;
    type WeightInfo    = pallet_bags_list::weights::SubstrateWeight<Runtime>;
    type BagThresholds = BagsThresholdsParam;
    type Score         = VoteWeight;
}

// ─── pallet-session ───────────────────────────────────────────────────────────
impl pallet_session::Config for Runtime {
    type RuntimeEvent         = RuntimeEvent;
    type ValidatorId          = AccountId;
    type ValidatorIdOf        = pallet_staking::StashOf<Runtime>;
    type ShouldEndSession     = Babe;
    type NextSessionRotation  = Babe;
    type SessionManager       = pallet_session::historical::NoteHistoricalRoot<Self, Staking>;
    type SessionHandler       = <SessionKeys as sp_runtime::traits::OpaqueKeys>::KeyTypeIdProviders;
    type Keys                 = SessionKeys;
    type WeightInfo           = pallet_session::weights::SubstrateWeight<Runtime>;
    type DisablingStrategy    = pallet_session::disabling::UpToLimitDisablingStrategy<3>;
}

impl pallet_session::historical::Config for Runtime {
    type FullIdentification    = pallet_staking::Exposure<AccountId, Balance>;
    type FullIdentificationOf  = pallet_staking::ExposureOf<Runtime>;
}

impl pallet_offences::Config for Runtime {
    type RuntimeEvent         = RuntimeEvent;
    type IdentificationTuple  = pallet_session::historical::IdentificationTuple<Self>;
    type OnOffenceHandler     = Staking;
}

impl pallet_authority_discovery::Config for Runtime {
    type MaxAuthorities = ConstU32<100>;
}

// ─── Custom pallet bridge structs ─────────────────────────────────────────────

pub struct RankedCollectiveBridge;
// V4: RankedCollective is active — bridge reads/writes real pallet storage.
impl pallet_agents::pallet::AgentCollective<AccountId> for RankedCollectiveBridge {
    fn induct(who: &AccountId) -> frame_support::pallet_prelude::DispatchResult {
        RankedCollective::do_add_member(who.clone())
            .map_err(|_| frame_support::pallet_prelude::DispatchError::Other("ranked-collective: induct failed"))
    }
    fn promote(who: &AccountId) -> frame_support::pallet_prelude::DispatchResult {
        RankedCollective::do_promote_member(who.clone(), None)
            .map_err(|_| frame_support::pallet_prelude::DispatchError::Other("ranked-collective: promote failed"))
    }
    fn rank_of(who: &AccountId) -> Option<u32> {
        pallet_ranked_collective::Members::<Runtime>::get(who).map(|m| m.rank as u32)
    }
    fn remove(who: &AccountId) {
        // do_remove_member_from_rank removes the member if their rank <= max_rank.
        // u16::MAX ensures removal at any rank (0, 1, 2, 3, ...).
        let _ = RankedCollective::do_remove_member_from_rank(who, u16::MAX);
    }
}

pub struct IdentityCapabilityBridge;
impl pallet_agents::pallet::IdentityHandler<AccountId> for IdentityCapabilityBridge {
    fn has_identity(who: &AccountId) -> bool {
        pallet_identity::Pallet::<Runtime>::has_identity(who, Default::default())
    }
    fn set_capability(who: &AccountId, capability_id: u32, active: bool)
        -> frame_support::pallet_prelude::DispatchResult
    {
        let _ = (who, capability_id, active);
        Ok(())
    }
    fn agent_has_capability(who: &AccountId, capability_id: u32) -> bool {
        let caps = pallet_agents::AgentCapabilities::<Runtime>::get(who);
        caps.binary_search(&capability_id).is_ok()
    }
}

pub struct OracleCapabilityGate;
impl pallet_oracle::CapabilityChecker<AccountId> for OracleCapabilityGate {
    fn agent_has_capability(who: &AccountId, capability_id: u32) -> bool {
        let caps = pallet_agents::AgentCapabilities::<Runtime>::get(who);
        caps.binary_search(&capability_id).is_ok()
    }
}

pub struct ValidatorCountBridge;
impl pallet_emissions::pallet::ValidatorCountProvider for ValidatorCountBridge {
    fn active_validator_count() -> u32 {
        pallet_staking::Pallet::<Runtime>::active_era()
            .map(|era| pallet_staking::ErasStakersOverview::<Runtime>::iter_prefix(era.index).count() as u32)
            .unwrap_or_else(|| pallet_staking::Validators::<Runtime>::count())
    }
}

pub struct OrchestratorEmissionsImpl;
impl pallet_emissions::pallet::OrchestratorEmissions<Balance> for OrchestratorEmissionsImpl {
    fn compute_weights(multiplier: u32) -> (u128, u32) {
        pallet_orchestrator::Pallet::<Runtime>::compute_era_orchestrator_weights(multiplier)
    }
    fn settle(orch_emission: Balance, orch_weight: u128) {
        if orch_weight > 0 {
            pallet_orchestrator::Pallet::<Runtime>::settle_orchestrator_era(orch_emission, orch_weight);
        }
    }
}

pub struct OrchestratorBridge;
impl pallet_agents::pallet::OrchestratorLookup<AccountId, Balance> for OrchestratorBridge {
    fn get_orchestrator(sub_agent: &AccountId) -> Option<AccountId> {
        pallet_orchestrator::SubAgentToOrchestrator::<Runtime>::get(sub_agent)
    }
    fn add_orchestrator_volume(orchestrator: &AccountId, amount: Balance) {
        pallet_orchestrator::Pallet::<Runtime>::add_orchestrator_volume(orchestrator, amount);
    }
}

/// ConvictionVoting implements GovVoteVerifier by checking whether the agent
/// has at least one active (non-empty) vote in any OpenGov referendum class.
/// An agent that has never voted, or whose votes are all empty, fails the check.
/// This prevents record_gov_vote() from being called without genuine participation.
impl pallet_agents::pallet::GovVoteVerifier<AccountId> for ConvictionVoting {
    fn is_actively_voting(who: &AccountId) -> bool {
        use pallet_conviction_voting::{Voting, VotingFor};
        VotingFor::<Runtime>::iter_prefix(who).any(|(_, voting)| {
            matches!(&voting, Voting::Casting(c) if !c.votes.is_empty())
        })
    }
}

pub struct AutoParamsImpl;
impl pallet_auto_params::pallet::AutoParamsProvider for AutoParamsImpl {
    fn completion_fee_bps() -> u32 { pallet_auto_params::Pallet::<Runtime>::live_completion_fee_bps() }
    fn alpha()              -> u32 { pallet_auto_params::Pallet::<Runtime>::live_alpha() }
    fn beta()               -> u32 { pallet_auto_params::Pallet::<Runtime>::live_beta() }
    fn floor_bps()          -> u32 { pallet_auto_params::Pallet::<Runtime>::live_floor_bps() }
    fn min_score_eligible() -> u32 { pallet_auto_params::Pallet::<Runtime>::live_min_score_eligible() }
    // V4: F-02 fix — run_era_rules is now called every settle_era
    fn run_era_rules(metrics: pallet_auto_params::pallet::EraMetrics) {
        pallet_auto_params::Pallet::<Runtime>::run_era_rules(metrics);
    }
}

pub struct EscrowCompletionFee;
impl frame_support::traits::Get<u32> for EscrowCompletionFee {
    fn get() -> u32 { pallet_auto_params::Pallet::<Runtime>::live_completion_fee_bps() }
}

pub struct OracleCounterBridge;
impl pallet_emissions::pallet::OracleCounters for OracleCounterBridge {
    fn drain_era_counters() -> (u32, u32) {
        pallet_oracle::Pallet::<Runtime>::drain_era_counters()
    }
}

// ─── Custom pallet configs ─────────────────────────────────────────────────────

parameter_types! {
    pub const AgentsMinStake:             Balance = 1_000 * CMN;
    pub const AgentsFullFloorStake:       Balance = 10_000 * CMN;
    pub const AgentsMaxStakePerAgent:     Balance = 1_000_000 * CMN;
    pub const AgentsUnstakeCooldown:      BlockNumber = 7 * DAYS;
    pub const AgentsBaseRegistrationFee:  Balance = 50 * CMN;
    pub const AgentsMaxRegistrationsPerBlock: u32 = 10;
    pub const AgentsMaxAgents:            u32 = 10_000_000;
    pub const AgentsRank3MinCompletions:  u32 = 50;
    pub const AgentsMinRank3OracleScore:  u32 = 1_000;
    pub const AgentsRank3SpanGate:        BlockNumber = 30 * DAYS;
    pub const AgentsMaxVolToStakeRatio:   u32 = 10;
    pub const AgentsHeartbeatGrace:       BlockNumber = HOURS * 18;   // V4: 3 eras grace (was 6h = 1 era — zero margin)
    pub const AgentsHeartbeatDecay:       BlockNumber = DAYS * 90;
    pub const AgentsMaxUriLen:             u32 = 256;
    pub const AgentsMaxNameLen:            u32 = 64;
    pub const AgentsMaxCapabilities:       u32 = 20;
    pub const AgentsMaxDelegationPeriod:   BlockNumber = 90 * DAYS;
    pub const AgentsSlashAppealWindow:     BlockNumber = 10;
    pub const OrchestratorMaxFeeBps:       u32 = 500;
    pub const OrchestratorLinkWindow:      BlockNumber = 7 * DAYS;
}

impl pallet_agents::Config for Runtime {
    type RuntimeEvent             = RuntimeEvent;
    type Currency                 = Balances;
    type MinStake                 = AgentsMinStake;
    type FullFloorStake           = AgentsFullFloorStake;
    type MaxStakePerAgent         = AgentsMaxStakePerAgent;
    type UnstakeCooldown          = AgentsUnstakeCooldown;
