import { defineConfig } from 'vitepress'

// Read the chain snapshot so the site header can advertise exactly which
// runtime the prose was verified against. `snapshot.json` is regenerated by
// `npm run snapshot:chain` against a live node — see reference/token-model.md.
import snapshot from '../.chain/snapshot.json'

export default defineConfig({
  title: 'Scalar Commons',
  description:
    'Coordination infrastructure for autonomous AI agents — node operation, agent SDK, RPC surface and the CMN token model.',
  lang: 'en-US',

  // The site lives in `docs/` alongside pre-existing engineering records that
  // are not part of the published documentation. They stay where they are.
  srcExclude: ['VERIFIED-CONSTANTS.md', 'rfcs/**', 'README.md'],

  // A broken internal link is a documentation bug, so fail the build on one.
  ignoreDeadLinks: false,

  cleanUrls: true,

  themeConfig: {
    nav: [
      { text: 'Run a node', link: '/guide/run-a-node' },
      { text: 'SDK', link: '/guide/sdk' },
      { text: 'RPC', link: '/reference/rpc' },
      { text: 'Token model', link: '/reference/token-model' },
      {
        text: `spec ${snapshot.runtime.specVersion}`,
        items: [
          {
            text: `Verified against ${snapshot.chain.name}`,
            link: '/reference/token-model#provenance',
          },
        ],
      },
    ],

    sidebar: [
      {
        text: 'Guide',
        items: [
          { text: 'Run a node', link: '/guide/run-a-node' },
          { text: 'SDK usage', link: '/guide/sdk' },
        ],
      },
      {
        text: 'Reference',
        items: [
          { text: 'RPC reference', link: '/reference/rpc' },
          { text: 'Token model', link: '/reference/token-model' },
        ],
      },
    ],

    outline: [2, 3],

    socialLinks: [
      { icon: 'github', link: 'https://github.com/tejaspatil1936/scalar-commons' },
    ],

    footer: {
      message: `Documented values verified against ${snapshot.chain.name} (spec ${snapshot.runtime.specVersion}).`,
      copyright: 'Scalar Commons — Apache-2.0',
    },
  },
})
